### ISSUE TITLE
xp orb crashes server

### ISSUE THREAD

**Issue by bobodoustaud** [OpenMods/OpenBlocks#1001]
crash report : https://pastebin.com/FGRDzZTJ

i think it's related to openblocks because the xp orb was created by an xp shower

**Comment by boq** [comment]
This is vanilla Minecraft mechanism that stops server after tick takes too long (in this case over minute). While it may be caused by too many entities (like xp orbs), it's not ~~related to~~ bug in OpenBlocks itself (might as well be mob farm gone wrong).
