### ISSUE TITLE
Stepping on a tank + xp drain caused server to crash.

### ISSUE THREAD

**Issue by MrZoraman** [OpenMods/OpenBlocks#1003]
I placed an openblocks tank and an xp drain on top of it. I stood on the drain and the server crashed. The error log is attached.

[crash log.txt](https://github.com/OpenMods/OpenBlocks/files/4332437/crash.log.txt)

I was using the [MCEternal](https://www.curseforge.com/minecraft/modpacks/minecraft-eternal/) modpack version 1.3.4.

**Comment by boq** [comment]
Seems like #974. If this is reproducible, please attach `level.dat` (if possible). Otherwise, is probably is registry corruption unrelated to OpenBlocks.

**Comment by MrZoraman** [comment]
When I started up the server the problem went away. I can try loading up a backup to see if it's reproduceable though.

**Comment by boq** [comment]
Then is sounds like #974. There is some runtime corruption in Forge's fluid registry and only common trait is that there is second mod that registers same fluid id (in this case, Cyclic, but they seem to do it correctly). Maybe there is third mod that does some weird things with that data.

Anyway, closing as duplicate, no need for attaching backups.
