### ISSUE TITLE
Apparently isn't compatible with OpenJDK9

### ISSUE THREAD

**Issue by Mineter4gret** [OpenMods/OpenBlocks#1009]
by process of elimination, I had my recent crash down to this mod and it's library counterpart. I run OpenJDK9 for performance reasons, and I encountered a bug with this and forge.  Heres my log file. I'm unsure if it was totally this mod, or both it and forge. Its working now that I removed the mod though.
[debug.log](https://github.com/OpenMods/OpenBlocks/files/4496720/debug.log)

**Comment by boq** [comment]
> Examining for coremod candidacy OpenModsLib-**1.7.10**-0.10.1.jar
You are using 1.7.10 version of OpenModsLib on 1.12, nothing to do with Java 9.

**Comment by Mineter4gret** [comment]
oops my bad haha sorry, honest mistake. Haven't slept for a while and I wasn't paying attention.
