### ISSUE TITLE
BIGBUTTON

### ISSUE THREAD

**Issue by xbxymax** [OpenMods/OpenBlocks#1010]
Place 'OPENBLOCKS' on the front of the 'DISPENSER' and activate, and the server will crash

**Comment by boq** [comment]
Please attach crash report.

**Comment by xbxymax** [comment]
[crash-2020-05-02_18.14.53-server.txt](https://github.com/OpenMods/OpenBlocks/files/4583497/crash-2020-05-02_18.14.53-server.txt)

**Comment by boq** [comment]
Minecraft 1.7.10 is 5 years, 10 months, and 9 days old today.
Also, that crash was fixed in bukkit/thermos/whatever about 4 years ago.
