### ISSUE TITLE
Crash when i stand on a painted block

### ISSUE THREAD

**Issue by omerbadawy11** [OpenMods/OpenBlocks#1011]
Hello, Firstly I'd like to say thank you for the amazing mod!
my issue is that I noticed that when I stand on a block that is labeled canvas I crash instantly and my game detects that it's Openblocks
Could you help me out?

https://privatebin.net/?976dc2d0e9167c7d#82RWKbxjV83aHmxSQDCrVDnfvZBw4HmbbPRDKT5vVCJp
The link above is the crash log.

**Comment by boq** [comment]
The problem seems to be in whatever "baritone" is.

**Comment by omerbadawy11** [comment]
I see, thank you
