### ISSUE TITLE
Modpack Crashing Bug

### ISSUE THREAD

**Issue by DasK18** [OpenMods/OpenBlocks#1013]
Was playing "Roguelike Adventures and Dungeons" Modpack on Twitch Mods. Looking at enchantment table and mousing over weapon and pressed a button on accident. Might've been 'ALT'. Then game crashed. Game crashes every time I open inventory now. Created new world and opening inventory crashes it now.
Uploading most recent file. I have like 10 other crash reports if needed.
[crash-2020-05-29_10.35.35-client.txt](https://github.com/OpenMods/OpenBlocks/files/4702874/crash-2020-05-29_10.35.35-client.txt)

**Comment by boq** [comment]
Duplicate of https://github.com/OpenMods/OpenBlocks/issues/948 - Optifine issue
