### ISSUE TITLE
[BUG] Thermal expansion and openblocks don't go pretty well :P

### ISSUE THREAD

**Issue by gh-doot** [OpenMods/OpenBlocks#1015]
Im just a new guy in github and in here, just never sent a bug so yeah. Sorry if I broke a rule or anything, I don't understand the rules sometimes due to poor english.
----------------------------------------------------------------ACTUAL-BUG------------------------------------------------------------------
Enough of that explanation.
![image](https://user-images.githubusercontent.com/48828036/86245758-024b7700-bbbb-11ea-96c1-394f95b27384.png)
Here is the 1st step to make.

2nd step is... 
![image](https://user-images.githubusercontent.com/48828036/86245850-29a24400-bbbb-11ea-9e79-6e9da1e29a89.png)
The beauty of the bug UnU. (stands for sad owo)

**Comment by gh-doot** [comment]
Plz halp >:

**Comment by gh-doot** [comment]
Any solution yet :P

version: full release on both openblocks and thermal expansion

**Comment by boq** [comment]
If you are talking about wrong rendering order, it's not something either of mods can fix, since it's issue with Minecraft itself. Also, for future reference, please limit bug reports to one comment.

**Comment by gh-doot** [comment]
thanks but the thing is how do i fix this rendering thingy? I don't want my youtuber viewers to get confused, so yeah.

**Comment by boq** [comment]
You can't, it has been in game since forever

**Comment by gh-doot** [comment]
rip then its actually closed for sur, thnx for the help tbh @boq
