### ISSUE TITLE
Has development stopped for this mod?

### ISSUE THREAD

**Issue by Jaeiya** [OpenMods/OpenBlocks#1017]
Checking the code frequency, every single branch is stale and the last update was 4 months ago on the 1.14 branch. So I'm just curious if work is still being done (in the background) or if I should look elsewhere for a similar mod to compliment my 1.15 server?

**Comment by boq** [comment]
I will work on it when I have time. When? No idea.

**Comment by Jaeiya** [comment]
Appreciate the response 👍
