### ISSUE TITLE
op_inventory restore doesn't restore baubles

### ISSUE THREAD

**Issue by iainvm** [OpenMods/OpenBlocks#1019]
A players grave was destroyed by a mob in the `MC Eternal` modpack using Openblocks version `1.8.1` and upon using the command to restore the inventory the baubles weren't restored. When graves have been on the ground they've restored baubles just fine. Seems to just be the command not working. 

Anyway of restoring this separately?

**Comment by boq** [comment]
This command can only work on inventories it knows about. While OpenBlocks has ability to plug-in non-vanilla inventories, no such integration was ever created for Baubles, so it is not saved.

Graves, on the other hand, are capturing all items that would otherwise be dropped, including baubles.
