### ISSUE TITLE
StoreContents is set to false but it still creates NBT files

### ISSUE THREAD

**Issue by ghost** [OpenMods/OpenBlocks#1025]
I've set both graves and storeContents to false, because on this server we have keep inventory on and therefore no need for either, but it still keeps creating files with names like inventory-username-datetimeofdeath.dat every time a player dies. I also have the same on single player, also with both settings turned to false. Am I overlooking something obvious or is this possibly a bug? Thank you very much!

Used versions:
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2854
 - Open Mods Lib: 0.12.2
 - Open Blocks: 1.8.1

**Comment by boq** [comment]
`inventory-` files are generated by separate functionality, controlled with `dumpDeadPlayersInventories`.

**Comment by ghost** [comment]
Thanks! I'll update our settings!
