### ISSUE TITLE
[1.12.2] Fix LittleTiles Cursor compatibility

### ISSUE THREAD

**Issue by CreativeMD** [OpenMods/OpenBlocks#1031]
Hey there,
I'm the author of LittleTiles and recently somebody told me that your feature the cursor does not work on it's blocks, which is not a big surprise. Maybe we can fix it together? Could you explain me how it works and would could possible be the cause of it?
LittleTiles is still 1.12 (will update it eventually), so if you don't support that version just let me know.

In Regards
CreativeMD

**Comment by boq** [comment]
Code is here: https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/item/ItemCursor.java#L78
Looking at it, I see two potential incompatibilities:
1. Action only being performed on server OR
2. (0,0,0) hit vector hitting edge case somewhere in handler.

**Comment by CreativeMD** [comment]
Oh, actually I misunderstood how the cursor works. Yeah ... it obviously fails because this is being done on server side. Unfortunately the server is not accurate enough to calculate which point the player is facing exactly, so I do these things client side and send a separate packet to the server to perform the action.

I would just leave in there, I don't think there is an easy fix it. Thanks for your time anyway!
