### ISSUE TITLE
[1.12.2]crash when looking in openblocks creative tab

### ISSUE THREAD

**Issue by tonimark** [OpenMods/OpenBlocks#1041]
go just to creative tab in open blocks and scroll down , you will eventually end with a crash :
crash log[crash-2021-07-06_18.26.14-client.txt](https://github.com/OpenMods/OpenBlocks/files/6771110/crash-2021-07-06_18.26.14-client.txt)
complete log https://paste.ee/p/09MIe

**Comment by boq** [comment]
Optifine issue: https://github.com/OpenMods/OpenBlocks/issues/948
