### ISSUE TITLE
Are there any plans to release a 1.19.2 version?

### ISSUE THREAD

**Issue by Lion4K** [OpenMods/OpenBlocks#1045]

**Comment by ThisIsACoolBoy** [comment]
no

**Comment by Lion4K** [comment]
I see.
Sad to see this awesome mod die.

Well, thanks a lot for all your hard work across the years! 

Best wishes!

**Comment by boq** [comment]
I'd like to point out that this answer did not come from contributor.
Closing to prevent misinformation.
