### ISSUE TITLE
Auto Enchantment Table (Can't Enchant over Lv 8)

### ISSUE THREAD

**Issue by dypref** [OpenMods/OpenBlocks#225]
Using 1.2.2.

The Auto Enchantment Table will drain the XP accordingly but it will only enchant the item if you drag the slider to a number between 1 and 8, 9 through 30 have no effect no matter the level of the EXP that the Auto Enchantment Table contains.

**Comment by Joey0826** [comment]
actually if you don't use drains what you do is that you make it a normal enchantment table
