### ISSUE TITLE
Config option to disable guide and changelog

### ISSUE THREAD

**Issue by Dreytac** [OpenMods/OpenBlocks#322]
Hey guys. I have a request for a config option to disable the guide and changelog being automatically given to each player.

The book has a recipe to make it if the player wants to use it so an option to turn it off by default shouldn't be to invasive.

**Comment by JasonPra** [comment]
I know this is closed but I felt like adding my own 2 cents in. I would like to have the option to disable spawning with it only because I want people to have to craft it that way they only have the book if they want to play with tinkers stuff.

**Comment by ryantheleach** [comment]
@JasonPra See the linked issue, it's in the config afaik.
