### ISSUE TITLE
Painting Blocks

### ISSUE THREAD

**Issue by jmarlo** [OpenMods/OpenBlocks#360]
This is one of two mods that I absolutely adore, but they aren't working together, which makes me sad. I am building a barn. Carpenters blocks lets me collapse a block to get the angle I want on the roof. Normally, I would use open blocks to paint just one surface of a block instead of the whole thing. But open blocks doesn't paint on carpenters blocks :(  Is there a config option (perused file but couldn't find) or a change in code that I could implement to make open blocks work on non-vanilla blocks? I'd be ever so grateful!

![2014-03-29_19 31 44](https://cloud.githubusercontent.com/assets/6764773/2559979/6259edba-b79a-11e3-9040-0ee44de034b3.png)

**Comment by superzanti** [comment]
I know this is a dead thread, but This is still something I'd love to have support for.

**Comment by boq** [comment]
Hmm, I can see two possibilities, but both need change in other mod: either implement `Block.recolourBlock` for support of OB brushes (but only basic 16 colours) or we can agree to other common interface that supports 24 bit colour (more or less something like [this](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/api/IPaintableBlock.java))
