### ISSUE TITLE
A Command For Lost Gravestones

### ISSUE THREAD

**Issue by harry-clarke** [OpenMods/OpenBlocks#391]
Please make a command so that if a gravestone can't be recovered an OP can return the items that a player lost on their last death, either in a gravestone next to the player, or straight into the player's inventory.
I'm not quite sure how to label this as a suggestion.

**Comment by boq** [comment]
Looks like I implemented that one some time ago. Check `/ob_inventory restore` (described in info book)

**Comment by trismegistis** [comment]
How do you use this command?

**Comment by boq** [comment]
It's described either in in-game info book or [FAQ](openmods.info/faq.html).
