### ISSUE TITLE
[REQ] Cursor should stop reseting everytime you right click on another block.

### ISSUE THREAD

**Issue by Fixided** [OpenMods/OpenBlocks#426]
I think the cursor should stop reseting everytime you right-click a block.
I have to go all the way back and shift+right-click again....

**Comment by GodsVictory** [comment]
Fairly easy fix, simply check that the player is sneaking first:

```
	@Override
	public boolean onItemUse(ItemStack stack, EntityPlayer player, World world, int x, int y, int z, int side, float hitX, float hitY, float hitZ) {
		if (player.isSneaking()) {
			NBTTagCompound tag = getItemTag(stack);
			tag.setInteger("dimension", world.provider.dimensionId);
			tag.setInteger("x", x);
			tag.setInteger("y", y);
			tag.setInteger("z", z);
			tag.setInteger("side", side);
		}
		return false;
	}
```

The return false allows the object to be activated when right clicking anywhere

**Comment by Fixided** [comment]
After a year and a half, is this feature still not a thing yet?

**Comment by Fayti1703** [comment]
Can you open a pull request for that, @GodsVictory ?
