### ISSUE TITLE
Radio-Mod messes up Streamingserver

### ISSUE THREAD

**Issue by Faldrian** [OpenMods/OpenBlocks#438]
Hello!

I'm Faldrian from TheRadio.CC and we have a problem with your plugin. Since some month ago (to be exact: mid-february) our listener statistics exploded and icecast2 began counting crazy connections.
We investigated that matter and found your plugin ( https://github.com/OpenMods/OpenBlocks/blob/075430abca511372722e486bbb52d54e98418f1c/src/main/java/openblocks/Config.java#L384 ) , but we also investigated the type of connections opened to our icecast-instance.

Situation:
Currently there are ~ 6 new connections per second, which are immediately terminated by the client. Unfortunately they are terminated in a way that our icecast-server stillt thinks there is an active connection and counts the connection towards the listener count. The TCP-handling of our server has to handle unneccesary amounts of dead connections, that are not corrently terminated.

We have made an ugly script to intercept these connections and force terminate them after they are only partially closed, removing ~30 broken connections per minute to keep our icecast-server from piling up dead connections.

What you can do / we would like you to do:
- Improve the correct termination of connections if the radio is turned of or switched or whatever you do in your plugin to stop listening.
- If that is not possible, please remove our stream from the config and push the new config to the people using the plugin or inform them. But we would strongly prefer that you fix your plugin to behave politely. :)

Thanks for adding us in the first place, but currently it makes us more trouble than generates interested new listeners.

Best wishes,
Faldrian

**Comment by cookta2012** [comment]
I have one question Boq why didn't someone consider to add a black list webpage that they can submit their stream url. So that when a crystal is made with that url it turns to a blank crystal.
