### ISSUE TITLE
Sprinker not working properly

### ISSUE THREAD

**Issue by UnPure** [OpenMods/OpenBlocks#468]
Hey there.
Currently using:
OpenBlocks-1.7.10-1.3-snapshot-428
OpenModsLib-1.7.10-0.6-snapshot-222
Seems like sprinkler are not working properly.
Atleast not the visual part.
Take a look at this video to see what happens:
https://www.youtube.com/watch?v=ue8sm9j4XcI
It seems like its still working the way it should.
Its just not creating the water particles to the correct direction.
Sorry for my bad english. I hope its not to hard to understand.

**Comment by nevercast** [comment]
Related: #617
