### ISSUE TITLE
Unable to sleep in bed / Sleeping in sleeping bag causes death by falling through world

### ISSUE THREAD

**Issue by darkphan** [OpenMods/OpenBlocks#531]
Snapshot 459, users are unable to sleep in a bed (says it is occupied) and when using a sleeping bag they fall through the world and die.

**Comment by b0bst3r** [comment]
Is this related to the max sleep height Y128?

I just tried sleeping above this height (where a normal bed just throws you back out of it) and the sleeping bag sent me straight into the void.

**Comment by boq** [comment]
This issue is probably no longer valid, since I changed that code few times already.

I can't reproduce your issue in recent version.

**Comment by b0bst3r** [comment]
That issue was using OpenBlocks-1.7.10-1.3-snapshot-549 sorry if it's old

**Comment by boq** [comment]
No, this snapshot is not old. But your problem is probably separate issue. Anyway, I can't reproduce, so it's probably interaction with other mod (or spigot if used)
