### ISSUE TITLE
Issue: Sprinklers don't seem to work right in 1.7.10 (direwolf20)

### ISSUE THREAD

**Issue by Danekjovax** [OpenMods/OpenBlocks#558]
I am using the direwolf20 modpack, and it appears that sprinklers aren't working well at all:

1) Water rendering shows it's only spraying a 3x9 block area, not a 9x9 area.
2) Plants being "watered" aren't getting growth tick acceleration bonuses, with or without bonemeal boost.  How I know this is I created a normal 9x9 garden plot, placed the sprinkler at one side of the garden, then planted wheat in all the squares, then watched the growth -- the "watered" area didn't grow the wheat any faster than the un-watered areas.

Thanks. ;2)

Version Info:
Java 1.8u25
MC 1.7.10
Modpack direwolf20 (FTB Launcher)
OpenBlocks-1.7.10-1.3-snapshot-433
OpenModsLib-1.7.10-0.6-snapshot-224

**Comment by nevercast** [comment]
Related: #617
