### ISSUE TITLE
Mass kicking issue

### ISSUE THREAD

**Issue by devryb** [OpenMods/OpenBlocks#559]
This error shows up and kicks everyone off the server often.

http://pastebin.com/uDen8HJ4

Dark Trilogy modpack v1.0.3

**Comment by Yselith** [comment]
Hello,

You found a way to solve it ?

**Comment by boq** [comment]
As I tried to explain, this is not our issue: players are already kicked when this log is written.

**Comment by Yselith** [comment]
I know boq :p i was asking to devryb.

**Comment by devryb** [comment]
It was a corrupted open mods config file on the client.

**Comment by devryb** [comment]
Sorry that comment is for
https://github.com/OpenMods/OpenModsLib/issues/29#issuecomment-68515142

What resolved this issue actually just ended up needing to restart the server and no issues since
