### ISSUE TITLE
Unable to see blocks in building guide + More

### ISSUE THREAD

**Issue by Fanofkatyperry** [OpenMods/OpenBlocks#571]
![2015-01-01_17 21 49](https://cloud.githubusercontent.com/assets/10366976/5593410/ad522c36-91da-11e4-96b2-ab7fb79c4377.png)
It wont show the blocks.. Also i cant seem to break blocks, does anybody know how to fix?

**Comment by boq** [comment]
sigh...

#546, #552. Also changelog. No idea about block breaking, but even if it is bug, it's not ours.
