### ISSUE TITLE
[ServerBug] Using World Domination with OpenBlocks book boots player to Lobby.

### ISSUE THREAD

**Issue by pyrocidious** [OpenMods/OpenBlocks#572]
Problem: When using the OpenBlocks info book whilst the cursor is highlighting a nearby block the player is kicked back to the lobby.
TempFix: Look at the sky or "air" before using the book.

This is on a Skyfactory 2.1 server (as standard no extras) however the book works in single player without any issues.

**Comment by boq** [comment]
Can't reproduce. Please check if you have most recent version and post logs (from server, if possible).

**Comment by pyrocidious** [comment]
http://pastebin.com/eGJa7vNU

I logged into the server opened the book whilst highlighting a block got kicked back to lobby,

I've copied the log data from the moment I joined to the moment just after I'm kicked.

By the looks of it, it might be an essentials conflict that I'm unaware of.
Any idea how to fix it at all? I'm stumped.

**Comment by boq** [comment]
I tried to reproduce it with cauldron-1.7.10-1.1207.01.198 (no idea what server you actually use, so I just grabbed something that looks recent) and I still can't reproduce. XMPPManager is red herring, but actual crash (starting at line 12) doesn't even contain our code.

Info book is coded exactly as vanilla's written book (just different GUI), so I have no idea why it fails.

**Comment by pyrocidious** [comment]
well thanks for looking into it, I wasn't sure where the conflict would be but that narrows it down at least, I'm trying to set up a server with a "hub" that you spawn in before you go and stand on a block to be teleported to your own island. It's not as easy as it should be haha

**Comment by boq** [comment]
Can you somehow post exact version of server you are using? I have no idea what exactly is in `NetHandlerPlayServer.java:946` but I can dump classes and decompile.

**Comment by pyrocidious** [comment]
cauldron-1.7.10-1.1236.05.212-server with the matching libraries from http://sourceforge.net/projects/cauldron-unofficial/files/1.7.10-latest/

**Comment by boq** [comment]
That was terribly weird bug. Vanilla was missing null check, but that branch was never executed. But slight modification in unrelated part triggered that on Cauldron servers.
