### ISSUE TITLE
Grave skeleton spam, in the Nether

### ISSUE THREAD

**Issue by seanterrorx** [OpenMods/OpenBlocks#586]
Hi I have noticed a issue with the mod ( or possibly a mod conflict). whenever me or one of the players on my server die in the nether a grave stone is spawned, this is as it should be. but the skeletons that spawn around a grave at night continue to spawn until the server crashes due to insane quantities. as a side note this only seams to occur in proximity to nether fortresses.
![2015-01-27_22 20 35](https://cloud.githubusercontent.com/assets/656668/5932486/201834e2-a674-11e4-8a8d-32b720c93578.png)

**Comment by Adaptivity** [comment]
I guess it is wrong mod. Is OpenBlocks spawns skeletons? It most likely https://github.com/NightKosh/GraveStone-mod problem.

**Comment by boq** [comment]
Well, our graves DO spawn skeleton (it was surprise to me too). Though it limits spawn rate to about one every minute and won't spawn, if there are more than 5 other mobs nearby. And I see no way it can work differently in nether and in vicinity of fortress.

I guess I can always add option to disable that.

**Comment by seanterrorx** [comment]
That would be very helpful, thank you for your rapid response
