### ISSUE TITLE
Xp shower tile entity missing std nbt tags

### ISSUE THREAD

**Issue by greenchem4** [OpenMods/OpenBlocks#587]

**Comment by greenchem4** [comment]
By this i measn the tile entity does not have the:
nbt::int x
nbt::int y
nbt::int z
and id tags
Although I have not seen any errors because of this missing tags in minecraft.  I will mention that it errors MCedit (I know it is no longer maintained) with key x not found.

**Comment by boq** [comment]
Looks like it was recreated at every load and Minecraft just silently ignored that.
