### ISSUE TITLE
Sky block not working correctly

### ISSUE THREAD

**Issue by bcatly** [OpenMods/OpenBlocks#588]
Hello. I would like to state a bug that seems to currently be occurring in 1.7.10. When the sky block is placed it is not the block that looks like a sky but the whole area. Here are 3 pictures to show you the situation.
![2015-01-31_15 42 21](https://cloud.githubusercontent.com/assets/6569219/5988679/5f48cbae-a962-11e4-9eae-7176315121fd.png)
![2015-01-31_15 42 28](https://cloud.githubusercontent.com/assets/6569219/5988680/5f4b9f14-a962-11e4-9e83-711498ffd6f1.png)
![2015-01-31_15 42 32](https://cloud.githubusercontent.com/assets/6569219/5988681/5f5032c2-a962-11e4-93b4-8aa9d58ccd7d.png)

**Comment by boq** [comment]
Can you provide exact version (and snapshot number if available)? 1.7.10 may be anything from current snapshot to ancient one in DW20 pack.

**Comment by bcatly** [comment]
tried the F3 + C but does not seem to be working on linux. The openblock version I am using is OpenBlocks-1.7.10-1.3 with the openlib version OpenModsLib-1.7.10-0.6

**Comment by boq** [comment]
F3-C is implemented in Minecraft, independent from operating system. Wiki suggests holding it for about 6 seconds.

I'm asking because OpenModsLib adds some info related to renders to crash report.

**Comment by bcatly** [comment]
Ah okay thank you. Here is the crash report.

**Comment by bcatly** [comment]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 1/31/15 6:10 PM
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1748)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['bcatly'/277337, l='MpServer', x=-90.72, y=77.62, z=-472.99]]
	Chunk stats: MultiplayerChunkCache: 81, 90
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (21,80,-545), Chunk: (at 5,5,15 in 1,-35; contains blocks 16,0,-560 to 31,255,-545), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Level time: 2524327 game time, 1706100 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 37 total; [EntityMinecartFurnace['entity.MinecartFurnace.name'/277011, l='MpServer', x=-125.84, y=78.50, z=-543.63], EntitySlime['Slime'/277798, l='MpServer', x=-0.28, y=-5.62, z=-33.01], EntityCustomNpc['Steven'/277084, l='MpServer', x=-36.53, y=72.00, z=-487.69], EntityPainting['Painting'/277022, l='MpServer', x=-98.00, y=76.50, z=-536.94], EntityCustomNpc['Rose'/277082, l='MpServer', x=-51.50, y=72.00, z=-509.50], EntityPainting['Painting'/277023, l='MpServer', x=-97.00, y=77.00, z=-538.06], EntityCustomNpc['Melanie'/277083, l='MpServer', x=-35.50, y=72.00, z=-493.50], EntityCustomNpc['Ruin'/277080, l='MpServer', x=-46.50, y=72.00, z=-507.50], EntityPainting['Painting'/277021, l='MpServer', x=-101.00, y=74.00, z=-538.06], EntityCustomNpc['Eirina'/277081, l='MpServer', x=-36.50, y=72.00, z=-508.50], EntityCustomNpc['Teleporter'/277062, l='MpServer', x=-57.50, y=98.00, z=-411.50], EntityCustomNpc['Kederath'/277061, l='MpServer', x=-60.50, y=72.50, z=-475.50], EntitySkeleton['Skeleton'/367014, l='MpServer', x=-19.50, y=45.00, z=-470.50], EntityCustomNpc['Stuart'/277060, l='MpServer', x=-53.53, y=82.00, z=-491.63], EntityCustomNpc['Carter'/277059, l='MpServer', x=-55.50, y=72.00, z=-509.50], EntityCustomNpc['Christine'/277058, l='MpServer', x=-60.50, y=72.00, z=-507.50], EntityCustomNpc['Teleporter'/277056, l='MpServer', x=-51.50, y=72.00, z=-517.50], EntitySheep['Sheep'/277000, l='MpServer', x=-159.81, y=72.00, z=-537.84], EntityMinecartChest['entity.MinecartChest.name'/277006, l='MpServer', x=-128.91, y=78.50, z=-543.56], EntityMinecartEmpty['entity.MinecartRideable.name'/277005, l='MpServer', x=-131.75, y=78.50, z=-543.25], EntityClientPlayerMP['bcatly'/277337, l='MpServer', x=-90.72, y=77.62, z=-472.99], EntityCustomNpc['Anna'/277040, l='MpServer', x=-71.50, y=72.00, z=-493.50], EntityCustomNpc['Kazimoto'/277041, l='MpServer', x=-71.50, y=72.00, z=-489.50], EntityPainting['Painting'/277024, l='MpServer', x=-101.94, y=76.00, z=-530.00], EntityPainting['Painting'/277025, l='MpServer', x=-97.00, y=76.00, z=-528.06], EntityPainting['Painting'/277021, l='MpServer', x=-101.00, y=74.00, z=-538.06], EntityPainting['Painting'/277023, l='MpServer', x=-97.00, y=77.00, z=-538.06], EntityPainting['Painting'/277022, l='MpServer', x=-98.00, y=76.50, z=-536.94], EntityZombie['Zombie'/385378, l='MpServer', x=-123.50, y=58.00, z=-482.50], EntitySpider['Spider'/280134, l='MpServer', x=-0.28, y=-5.62, z=-41.01], EntityPainting['Painting'/277025, l='MpServer', x=-97.00, y=76.00, z=-528.06], EntityPainting['Painting'/277024, l='MpServer', x=-101.94, y=76.00, z=-530.00], EntityCustomNpc['Pegato'/277026, l='MpServer', x=-107.50, y=72.00, z=-543.50], EntityCustomNpc['Bloodveld'/277033, l='MpServer', x=-88.50, y=72.00, z=-479.50], EntityCustomNpc['Lucy'/277035, l='MpServer', x=-86.50, y=75.50, z=-474.50], EntityCreeper['Creeper'/418723, l='MpServer', x=-19.50, y=45.00, z=-468.50], EntityCustomNpc['Mia'/277039, l='MpServer', x=-66.50, y=72.00, z=-508.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.8.11
	Java Version: 1.6.0_33, Sun Microsystems Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Sun Microsystems Inc.
	Memory: 327679864 bytes (312 MB) / 862486528 bytes (822 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1232 Minecraft Forge 10.13.2.1232 Optifine OptiFine_1.7.10_HD_U_A4 22 mods loaded, 22 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FML{7.10.85.1232} [Forge Mod Loader] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forge{10.13.2.1232} [Minecraft Forge] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	OldModelLoader{1.0} [OldModelLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NotEnoughItems{1.0.3.78} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.78-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AutoSapling{1.0} [AutoSapling] (Auto-Sapling-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	betterstorage{0.11.3.123} [BetterStorage] (BetterStorage-1.7.10-0.11.3.123.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	customnpcs{1.7.10b} [CustomNpcs] (CustomNPCs_1.7.10b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	lmmx{1.0} [lmmx] (littleMaidMobX-1.7.10_0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	MMMLibX{1.7.x-srg-1} [MMMLibX] (littleMaidMobX-1.7.10_0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	zabuton{1.0} [zabuton] (littleMaidMobX-1.7.10_0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Waila{1.5.5} [Waila] (Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	nolpfij_wildycraft{1.7.2} [Wildycraft] (wildycraft-1.7.10-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
	OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:FINISHED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Mesa DRI Intel(R) Haswell Mobile  GL version 3.0 Mesa 10.1.3, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by boq** [comment]
I see few possible causes:
- optifine - usual suspect when rendering is broken
- interactions with other mods - less possible (maybe adding `-Dforge.forceDisplayStencil=true` to minecraft command line can help?)
- drivers? probably not, but it's always worth updating

**Comment by killerscorpion** [comment]
Was having this same problem when i saw this on the closed issues. I just wanted to confirm that having Shaders installed makes this problem with skyblocks happen. Optifine still works fine with it.
