### ISSUE TITLE
OpenBlocks + Lib crash

### ISSUE THREAD

**Issue by ShteinCoder** [OpenMods/OpenBlocks#589]
http://pastebin.com/cBun0P23

Using latest development build of OpenBlocks and OpenModsLib.
Thanks!

**Comment by boq** [comment]
So why exactly it's our fault and not something called `Improving-Minecraft-Mod-1.7.10.jar`?

**Comment by ShteinCoder** [comment]
Apologies, I'm not the best at reading stacktraces.
