### ISSUE TITLE
Again: [Bug] Opening the book crashes the game back to the menu

### ISSUE THREAD

**Issue by Voidi** [OpenMods/OpenBlocks#592]
Opening the "World dominations with OpenBlocks" book crashes the game back to the menu

Minecraft Version: 1.7.10
Forge Version: 10.13.2.1230
OpenBlocks: 1.7.10-1.3
OpenModsLib: 1.7.10-0.6

Seems to only occur if you play on a dedicated Server

Crashlog
https://gist.github.com/Voidi/2b8818c5f60352eebd69

**Comment by boq** [comment]
This happens when you remove recipes, instead of disabling items/blocks. Also, fixed in snapshots.
