### ISSUE TITLE
Crash with Ender Storage

### ISSUE THREAD

**Issue by Neodark7** [OpenMods/OpenBlocks#597]
http://pastebin.com/QMdGZtpY

OpenBlocks-1.7.10-1.3-snapshot-560
OpenModsLib-1.7.10-0.6-snapshot-308
EnderStorage-1.7.10-1.4.5.27-universal

**Comment by boq** [comment]
Yeah, but what block have you placed nearby?

**Comment by Neodark7** [comment]
adjacent to chest woot ? this crash happen when i log into my server i really don't know :/ i have some OB tanks with milk connect to a MFR rancher, some ender tanks on a liquid transfert node from ExtraU

**Comment by boq** [comment]
You have at least one OpenBlocks block adjacent to chest. If possible, please downgrade to release and check.

**Comment by Neodark7** [comment]
ow yeah i've forgot, an ender tanks with OB liquid xp on top on 3 OB tanks sorry ^^

**Comment by boq** [comment]
Ok. Now, do you have stacktrace in logs (before crash) containing `Notice: Error creating tile entity`? If you can find it, can you post it here?

**Comment by Neodark7** [comment]
owe hmm i check that

**Comment by Neodark7** [comment]
http://pastebin.com/YET45i1A :)

**Comment by boq** [comment]
OpenModsLib-1.7.10-0.6-snapshot-**306**.jar != snapshot **308**.

**Comment by Neodark7** [comment]
oops derp
