### ISSUE TITLE
Gravestone + Buildcraft's Quarry.

### ISSUE THREAD

**Issue by Alexmaster50** [OpenMods/OpenBlocks#602]
When I fell into my quarry, I died of fall damage.
My grave spawned correctly, however upon being mined by the quarry non of the items were in the output chests of my quarry.
I tested this 2 more times and it didnt output my items.

**Comment by boq** [comment]
Reference to BuildCraft/BuildCraft#2472

**Comment by Adaptivity** [comment]
Fixed in BC. Can be closed.
