### ISSUE TITLE
console spam latest openblocks on jenkins

### ISSUE THREAD

**Issue by crunkazcanbe** [OpenMods/OpenBlocks#603]
http://pastebin.com/fxDufJqz

Thank you!

-Crunk

**Comment by boq** [comment]
Not our issue: [here](https://github.com/jakimfett/Minechem/commit/7b06338b85c5eda5fc060a0789e659ae58390926#diff-0f6f1f83534531b7c8115503b0bbd3e6R215) is line that is causing it (though it was removed in later builds).

Our class is called `openblocks.common.DonationUrlManager`. They want `openblocks.common.DonationURLManager`. Java is case-sensitive.

Also, we have [IMC handler](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/OpenBlocks.java#L485) for that purpose.
