### ISSUE TITLE
Improve tank/trophy localization, again

### ISSUE THREAD

**Issue by Adaptivity** [OpenMods/OpenBlocks#605]
This is just suggestion which you might want to implement. What do you think about changing filled tanks(tanks with fluids) name to just "Tank" but with tooltip like Contains(Filled with): "Fluid name"? I guess these names will look a bit better. And for the trophies you can make: Trophy and tooltip Entity: "Entity name"

**Comment by boq** [comment]
It was behaving like that before but I changed it when I added filled tanks and all trophies to creative inventory. If they were all just called `Tank`, then searching for `water` would never return them.

**Comment by Adaptivity** [comment]
It should return them. Because search system working for tooltips too as I know if tooltip not hidden of course.

**Comment by boq** [comment]
Just checked, and yes, you are right.

Anyway, I think that "X Tank" looks better in English and I will probably stick with it.

But yes, I'm aware that other languages have more difficult rules and it's impossible to get with simple substitution from "вода" to adjective "водный" or genitive case "воды"  (it is genitive case for "для", right? It's accusative for Polish equivalent "zbiornik na wodę").

**Comment by Adaptivity** [comment]
Well, I have no problems with translation since you added %s, I just thought it will look a bit better (it's still better for me but it's a minor thing)
