### ISSUE TITLE
Luggage rendering problem?

### ISSUE THREAD

**Issue by extern56** [OpenMods/OpenBlocks#611]
Also in NEI the luggage appears invisible...
It does this when I try to make the luggage...
Log:

```
[B#282]  [13:53:05] [Client thread/ERROR]: Couldn't render entity
[B#282]  java.lang.NullPointerException
[... snip ... - no point on pasting few hundred identical lines - B]
[B#282]  [13:53:20] [Client thread/ERROR]: Couldn't render entity
[B#282]  java.lang.NullPointerException
[B#282]  [13:53:20] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiIngameMenu
[B#282]  [13:53:20] [Client thread/ERROR]: Couldn't render entity
[B#282]  java.lang.NullPointerException
[...snip...]
[B#282]  [13:53:20] [Client thread/ERROR]: Couldn't render entity
[B#282]  java.lang.NullPointerException
[B#282]  [13:53:20] [Client thread/ERROR]: Couldn't render entity
[B#282]  java.lang.NullPointerException
[B#282]  [13:53:20] [Client thread/ERROR]: Couldn't render entity
[B#282]  java.lang.NullPointerException
[B#282]  [13:53:20] [Client thread/ERROR]: Couldn't render entity
[B#282]  java.lang.NullPointerException
[B#282]  [13:53:20] [Client thread/ERROR]: Couldn't render entity
[B#282]  java.lang.NullPointerException
```

**Comment by boq** [comment]
Now, after I removed few hundreds of identical lines and changed title to less shouty, can just calmly put exact version of OpenBlocks, OpenModsLib and if you use Optifine, FastCraft, etc?

**Comment by boq** [comment]
Also, any stacktrace that is NOT SINGLE LINE might help.

There should be one somewhere around start of logs. Or just start minecraft with -XX:-OmitStackTraceInFastThrow in JVM args

**Comment by extern56** [comment]
http://pastebin.com/aCEwHCzq
(Couldn't paste it here)

**Comment by boq** [comment]
```
am2.utility.RenderUtilities.setupShrinkRender(RenderUtilities.java:104)
```

Unsafe code in ArsMagica2 - [this](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/client/renderer/entity/EntityLuggageRenderer.java#L17) line is executed before they install their event handler on `EntityEvent.EntityConstructing`.

Not really fixable on my part.

**Comment by arnol372** [comment]
As an fyi for people who google their way here: The unsafe Ars Magica 2 code is in version 1.7.10_AM2-1.4.0.008. The luggage is visible in version 1.7.10_AM2_1.4.0.006.
