### ISSUE TITLE
Crash on load up

### ISSUE THREAD

**Issue by AgentGazey** [OpenMods/OpenBlocks#612]
I have tried and tried again to fix this but nothing works please help, TY :)

Crash log:
http://pastebin.com/vETWR2gD

**Comment by Xiretza** [comment]
Maybe try updating OpenModsLib?

**Comment by boq** [comment]
Other way:
```
OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-319.jar)
OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar)
```
Download OpenModsLib from openmods.info.
