### ISSUE TITLE
Fix for the tank/fluid alpha textures

### ISSUE THREAD

**Issue by ultrasn0w** [OpenMods/OpenBlocks#616]
Hi OpenMods devs,
I've seen that your tank/fluid alpha textures are not working as intended (https://i.imgur.com/HFSbYme.jpg).
GregoriusT, the dev of GregTech, also had this alpha texture problem, but he was able to fix it.
I though this would be of interest for you guys: http://forum.industrial-craft.net/index.php?page=Thread&postID=182222#post182222
If not, just close and ignore.

Greetings
ultrasn0w

**Comment by ultrasn0w** [comment]
The solution was no solution, pls ignore this.

**Comment by boq** [comment]
Yup. This snippet was for blocks (which automatically solve transparency issues out of box). Tank liquids are rendered as tile entities, so face sorting is unavailable.
