### ISSUE TITLE
Sprinkler visuals in need of fix

### ISSUE THREAD

**Issue by MrFestis** [OpenMods/OpenBlocks#617]
From what I've observed, the sprinkler hydrates a 9x9 area of tilled soil centered on the sprinkler block, however the visual particle effects of the sprinkled water drops leaving the sprinkler only covers a 3x9 area. It would be nice if the visuals respresented the actual hydration in game, extending to 9x9, as I recall that it used to do back in MC 1.6.4.

**Comment by boq** [comment]
Sprinkler's area of effect is configurable, so there is no universal set of parameters. I could figure that out, but I'm too lazy today :P

Anyway, after bce44df35f7b92155fc91925ead1e302f0c65a26 spray should at least cover default 9x9.
