### ISSUE TITLE
The text in the info book is complelely unrecognizable when "Force Unicode" is turned on

### ISSUE THREAD

**Issue by oldjunyi** [OpenMods/OpenBlocks#621]
Also, if the locale is set to some language like Chinese, Japanese. Whether or not the "Force Unicode" option is turned on, the characters in the book are always extremely small.

![a](https://cloud.githubusercontent.com/assets/641817/6768670/e68688c6-d0b4-11e4-820e-53a7a036bc78.png)

As a suggest, the scale ratio for any text in a mod should not be less than 1.0x.

**Comment by ajloveslily14** [comment]
Well dont turn on force-unicode silly

**Comment by boq** [comment]
@ajloveslily14 I don't think such comments help anyone. Please comment only when you have something constructive to say

/me puts off official hat

Anyway, I don't have that much control over text rendering and I'm not willing to implement my own solution.

Minecraft lack of anti-aliasing and proper scaling is causing problems even in vanilla (try setting GUI scale to small with forced Unicode).

And I'm not changing scale of that text. There is not enough space to even basic information.

So it's compromise. I'm not happy with that, but it's currently only solution. It may be broken, but only for small percent of configurations (~5% of clients that use languages with non-latin alphabet).

**Comment by AnrDaemon** [comment]
> So it's compromise. I'm not happy with that, but it's currently only solution. It may be broken,
> but only for small percent of configurations (~5% of clients that use languages with non-latin alphabet).
Pretty please, http://www.joelonsoftware.com/articles/Unicode.html before posting such replies.
Also, if this: ![javaw-20150515-195614 54](https://cloud.githubusercontent.com/assets/6532485/7657699/b0653bcc-fb3c-11e4-80c0-5c63294ed3c5.jpg)
is your definition of "readable", my definition of "readable" disagree with yours.
There's no excuse for not supporting proper unicode in 21'st century. There was none in the previous century, too, but that is a dicussion for another day.

**Comment by boq** [comment]
`reading_comprehension--`

I never said I was against Unicode or that's not supported. I was just pointing out that Minecraft font renderer is broken (even in vanilla itself), but I'm not willing to pull alternative font renderer with few kLOC of code and possibly mismatched license for that purpose.

Also, text on your image is readable. Not pretty, but readable.

**Comment by oldjunyi** [comment]
I added a locale-related config options to the *.lang files of OpenModsLib.

Now different language environment can have different text scaling and line space. Under current config settings, it will only enlarge the Chinese chacterers, leaves other languages' font unchanged.

It may not be the best solution, but at least, seems OK.

Before:
![2015-05-16_15 19 08](https://cloud.githubusercontent.com/assets/641817/7665255/cf0fb3b8-fbe1-11e4-9dc9-20e5fc6e52ef.png)

After:
![2015-05-16_15 17 46](https://cloud.githubusercontent.com/assets/641817/7665259/d95c9d68-fbe1-11e4-9f6a-885d7cb3828d.png)

**Comment by boq** [comment]
Now that's nice idea. Merged.

**Comment by AnrDaemon** [comment]
> Also, text on your image is readable. Not pretty,

"Not pretty" is the single worst possible offense you could do the the wriiten word.

**Comment by nevercast** [comment]
"wriiten word"

**Comment by AnrDaemon** [comment]
Yes, sorry. Somehow, it happens to me when I type doubled letters. Not all of them are caught before posting.
