### ISSUE TITLE
Skybocks do not  render properly

### ISSUE THREAD

**Issue by SneakyDevil** [OpenMods/OpenBlocks#623]
So I decided to make a nice little house underground and make the whole thing seem like its above ground using inverted skyblocks...however the ISB only shows dull solid colors like orange or blue. I did not realize something was up until a friend mentioned how it was so cool that he could see the star underground. this is what it currently looks like to me.
![2015-03-23_18 08 45](https://cloud.githubusercontent.com/assets/11374726/6791720/ac17f1ec-d187-11e4-9843-d0e699adf234.png)

**Comment by ajloveslily14** [comment]
This could be because 1. the sun just isnt in that position 2. your video settings might be doing that and 3. someone might have made a nono :fearful:

**Comment by boq** [comment]
OpenBlocks attaches some information to crash reports. Please force client crash (may be even on empty, test world) by holding F3+C for few seconds..

**Comment by SneakyDevil** [comment]
@ajloveslily14 Well, I asked my friend to show me his video settings(through share screen) and i copied them exactly, he was seeing stars...while I continued to see that.

@boq here you go
http://pastebin.com/pXJnc0Uy Minetweaker log
http://pastebin.com/86srkSNQ Crashreport from crash-report folder
https://drive.google.com/file/d/0B9X88iyYj6CpV3dwcV9Yb1pZLTA/view?usp=sharing Link to fml-client-latest.log(pastebin crashed)

**Comment by boq** [comment]
Hmm, have you tried to run it without CoFHCore? I recently noticed they are doing risky stuff with stencil buffer.

**Comment by boq** [comment]
Ok, I was able to reproduce it will CoFHCore. Fix already added to OpenModsLib.

**Comment by SneakyDevil** [comment]
So...update the Lib?

**Comment by ajloveslily14** [comment]
Yes

**Comment by SneakyDevil** [comment]
Rodger that

**Comment by SneakyDevil** [comment]
Errr....please explain to the github noob how to update through github?

**Comment by nevercast** [comment]
[Official Releases](http://www.openmods.info)
[Snapshots](http://www.openmods.info:8080/)

**Comment by SneakyDevil** [comment]
Right. Jenkins. Thanks.
