### ISSUE TITLE
Crash with game starting

### ISSUE THREAD

**Issue by MoofMonkey** [OpenMods/OpenBlocks#625]
when starting the game it immediatly crashes.
So it doesn't even open the minecraft 1.7.10 window
here is the log
Crash report: http://pastebin.com/GjMHkLh4
OpenBlocks version - github's recommended (OpenBlocks-1.7.10-1.3-snapshot-573.jar)

**Comment by boq** [comment]
Missing OpenModsLib.

**Comment by MoofMonkey** [comment]
Thx :)
