### ISSUE TITLE
Building Guide Text in OpenBlocks Book cutoff

### ISSUE THREAD

**Issue by agowa338** [OpenMods/OpenBlocks#626]
The Text in the OpenBlocks Book for the Building Guide ends abruptly after
"When in creative mode you can place an obsdian block above, then hit the building guide whit any".

And what is "obsdian" does it mean obsidian or is there another block?

**Comment by nevercast** [comment]
That would be a typo, yes it means Obsidian.

**Comment by boq** [comment]
Fixed typo, cutoff was fixed some time ago.
