### ISSUE TITLE
Dupey with OpenBlocks and Battlegear2

### ISSUE THREAD

**Issue by zHawky** [OpenMods/OpenBlocks#628]
Hello everyone, just now i can duping, when im have dual wielding swords then clicking in same time on bagage i can got two instead one, heh..

**Comment by boq** [comment]
Oh boy, little bit too informal, took me some time to parse.

Anyway, just linking to issue on other mod: Mine-and-blade-admin/Battlegear2#175.

**Comment by zHawky** [comment]
Well if that, sorry for my english, im still learning..

**Comment by zHawky** [comment]
Actually is fixing, close that issue.
