### ISSUE TITLE
Rendering glich with stacked /dev/null

### ISSUE THREAD

**Issue by masonpinder** [OpenMods/OpenBlocks#629]
I found that if you get a dev null, and put another dev null in that, and then put that in a dev null, get that thing and put it in a devnull, and do it about 16 times i think. It sort of makes your GUI go completely invisible (text chat, Pause menu, INVENTORY, hotbar...) Now, note that as soon as you throw the item out of your inventory, you can see your inventory again. But that can be quite tedious... And hard to tell that is why your inventory is invisible, when you are on a server. I say that you may need to put a blacklist on the devnull that it cant take a devnull into a devnull more than twice?

I was never griefed by this, but I found it and had the first intention of "Hey, this can be a HORRIBLE griefing tool, just like tinkers' auto-banning bombs...) So, you may want to fix that. THANKS!

**Comment by boq** [comment]
title == clickbait much :P

**Comment by nevercast** [comment]
That was rather fast, excellent @boq

Yes very much clickbait. It's as bad as the word 'dupe'
