### ISSUE TITLE
[Bug?] Elevators won't work properly

### ISSUE THREAD

**Issue by PawnedSauce** [OpenMods/OpenBlocks#634]
I currently just placed to elevators and then when I try to use them regularly it cannot elevate. In this situation block are between the 2 elevators and yes they are aligned properly on the same X level but when I clear all the block between them it works. I have even set the config to allow pass-through blocks set to "-1". The distance between the 2 elevators are 10 blocks exactly.

OpenBlocks version = 1.7.10-1.4
Current config = http://pastebin.com/fyVK4Gyd
EDIT: I threw in my config just in case

**Comment by boq** [comment]
Can't reproduce. Though I noticed that description of `maxPassThrough` is inaccurate - -1 is no longer special value (there was no need for it, since world has limited height, so setting in to 256 has same effect)

**Comment by VADemon** [comment]
I don't know if anything changed since then, but the world height isn't limited anymore, 256 is just the default

**Comment by boq** [comment]
Hmm? It never was more than 256. Few mods existed that tried to bypass it, but I'm not aware of any that was semi-usable and popular.

I may return option to ignore blocks, but as separate flag.

**Comment by Trayaurus** [comment]
So putting 256 would fix it? Because what's the cause is that it doesn't let me elevate when there is a single block between the elevators (any type of block)
I also changed that config to 100 still nothing - it is only 10 blocks apart

**Comment by boq** [comment]
As I said, I can't reproduce this issue. I checked default config and few modifications (in number of skipped blocks and search distance), including your config (with maxPassThrough > 0) and everything works as it should.

So only thing left is standard check-list:
- config changed on server and not on client
- XP drain (I see you disabled that)
- invisible blocks (railcraft?)

**Comment by nevercast** [comment]
Side Note: Do we know if the Railcraft tracker blocks do affect the function of the elevator? Is they do should the elevator ignore any block that can be placed over (Like tall grass and other blocks)

**Comment by boq** [comment]
Railcraft tracker blocks properly implement `Block.isAir`, so they are not a problem. I'm more worried about various "light" blocks for flood-lighting.

**Comment by Vastrix** [comment]
Same issue here! :(
It sometimes works and sometimes doesn't :(

Gonna try the latest snapshot..

**Comment by Vastrix** [comment]
Updated to Snap607 and disabled draining xp on usage (which was enabled by default for some reason :/ silly me..) fixed it :)

**Comment by boq** [comment]
XP drain was enabled at least since early MC 1.6.4 versions. I recently disabled this, since I was getting tons of bogus bug reports.
