### ISSUE TITLE
Tank Crash

### ISSUE THREAD

**Issue by XBlackLeopardX** [OpenMods/OpenBlocks#636]
When i break tanks filled with xp I get this crash when breaking a few idk about just breaking 1 then waiting but when breaking several one after another it causes the client to crash

https://gist.github.com/XBlackLeopardX/16fd1c05d80d500efde1

Edit: I am breaking it with tinker construct tools havent tried with vanilla tools and also if you break them slowly then it doesnt cause the crash as in wait a few seconds between breaking them

**Comment by boq** [comment]
#607, #633 duplicated
