### ISSUE TITLE
Can't See Building Guide

### ISSUE THREAD

**Issue by fcpwiz** [OpenMods/OpenBlocks#637]

**Comment by boq** [comment]
Needs redstone.

**Comment by fcpwiz** [comment]
Even in openblocks 0.3?

**Comment by boq** [comment]
Yes. We have [changelog](https://docs.google.com/document/d/1BqSDxmUuZduNjD4ST8fAYw02-USRynQP31AbYn1UKcw/edit), you know?

**Comment by fcpwiz** [comment]
Ah ok! Thank you!
