### ISSUE TITLE
Creative spawned tanks and player made tanks don't allow liquid extraction with buckets

### ISSUE THREAD

**Issue by Ianaver** [OpenMods/OpenBlocks#640]
I am using the latest snapshot and tanks are not allowing me to use buckets to take out the fluid, mod fluids or vanilla out of tanks.

**Comment by boq** [comment]
Sorry, I'm unable to reproduce. Can you run event log from here: http://openmods.info/misc.html, try to use bucket on tank, run command from description and post result somewhere?

**Comment by Ianaver** [comment]
k one sec

**Comment by Ianaver** [comment]
here: http://pastebin.com/mRw5vZpY

tried without anything else except: openblocks, openmods lib, codechickencore, NEI and the issue persisted

**Comment by Ianaver** [comment]
eventlog too ofcoarse :P

**Comment by Ianaver** [comment]
this most likely won't help too much but here it is:
(client log)

http://pastebin.com/ZXmUNWKx

**Comment by Ianaver** [comment]
@boq not sure what you did but thank you very much! the tanks are now working in the latest fix (606)!

:D

**Comment by boq** [comment]
No changes in tanks since last (1.4.1) release...

**Comment by Ianaver** [comment]
@boq strange... well something must have been messing with the tanks since they seem to work now so thx anyways :)
