### ISSUE TITLE
HQM lives spent, player banned, no gravestone?

### ISSUE THREAD

**Issue by tgstyle** [OpenMods/OpenBlocks#646]
So I have noticed an interesting trend on my server. When a player expends their last life in HQM, it bans them on death and no gravestone seems to spawn.

Why does it matter? I have given them the option to beg someone to give them a life and then I will pardon them and transfer a life from the player that offered.

**Comment by boq** [comment]
I will repeat what I'm repeating all such threads: graves contain only items that would normally drop. No more, no less. So if something grabs items before grave stores them - they are gone. So probably even if graves were disabled, nothing would drop from such players. We don't handle special cases, mod interactions, backpacks, containers, etc. We just store drops.

If you want to investigate, OpenBlocks logs in recent versions what happened to items and grave, after every death. Also, contents of graves and inventories just before death can be restored (see [FAQ](http://openmods.info/faq.html) for instructions).

**Comment by ryantheleach** [comment]
Pretty sure the player never finishes dying in multiplayer HQM, I've respawned players and they kept their inventory I think.

What happens is they get kicked and banned and the entity is saved out / lost before it gets a chance to die.
