### ISSUE TITLE
Block Breaker Dupe Bug

### ISSUE THREAD

**Issue by SirWilli** [OpenMods/OpenBlocks#649]
If the block in front of the block placer get broken by a block breaker for example the one from openblocks it will place the block again but it also keeps the item. 
This seems to only work with the combination of OpenBlocks breaker and MFR placer. Useing a other breaker or placer doesn't reproduce this issue.

Setup:
http://i.imgur.com/rzAZ0HS.png

**Comment by boq** [comment]
Ok, so I've decided to delay block breaking little bit. Even though I don't think MFR is 100% innocent (see post in other issue), it will be more effective if I protect against it on my side.

**Comment by SirWilli** [comment]
Thanks!
