### ISSUE TITLE
Build guide doesn't show the guide blocks

### ISSUE THREAD

**Issue by Nikkolino99** [OpenMods/OpenBlocks#653]
When placing the build guide in the world, it doesn't show the guide blocks for none of the builds,
I tried placing it in a new generated world, but it doesn't change, the version I have installed is 1.4.3-snapshot-626, I am writing here because I don't know how to code java and mods in general, I hope that someone can help me, thank

**Comment by boq** [comment]
This is generally good place for reporting potential bugs.

But your question was already asked enough times to be added to [FAQ](http://openmods.info/faq.html). Look under "Why doesn't building guide show any markers?".

**Comment by nevercast** [comment]
[So many times](https://github.com/OpenMods/OpenBlocks/search?q=Guide&type=Issues)
