### ISSUE TITLE
Tank Duping Glitch

### ISSUE THREAD

**Issue by awesome6089** [OpenMods/OpenBlocks#664]
I found a way to dupe tanks indefinitely

To Reproduce

1. Take a tank and place it

2. Place a sprinkler on the tank

3. Mine the Tank

The sprinkler should instead drop as an empty tank.

Openblocks Version: `OpenBlocks-1.7.10-1.4.3`

Manifest.MF:
```
Manifest-Version: 1.0  
Jenkins-Build: true  
Jenkins-Tag: jenkins-OpenBlocks-625  
Jenkins-ID: 2015-05-09_19-08-40  
Git-Branch: master  
Git-Hash: bca6e70  
FMLCorePlugin: openblocks.OpenBlocksCorePlugin  
FMLCorePluginContainsFMLMod: true
```

**Comment by boq** [comment]
Fixed in OpenModsLib.
