### ISSUE TITLE
The Height map projector shown wrong texture/color for gravel

### ISSUE THREAD

**Issue by warriorsofcats** [OpenMods/OpenBlocks#665]
I have biomes nearby in my world that have gravel cover the ground, and it is strange to see sand color over where gravel should be.

Let me know if you need anymore info.

**Comment by boq** [comment]
Sorry, it's the same color as vanilla maps. And I'm not patching vanilla.

**Comment by warriorsofcats** [comment]
Oh, I didn't know that one.
Oh well
