### ISSUE TITLE
[Suggestion] Add Torus shape to building guide

### ISSUE THREAD

**Issue by utoc** [OpenMods/OpenBlocks#668]
Good morning,

I'd like to request that a [Torus](https://en.wikipedia.org/wiki/Torus) shape be added to the building guide.  The information it will need is radius and thickness and then it can project the donut shaped object from the center, being the building guide itself.  Thank you for your consideration :)

**Comment by Gowcu** [comment]
In addition to this, would it be possible to put a GUI on this block to make it easier to use any new features such as the torus.
