### ISSUE TITLE
Sleeping bag dupe glitch

### ISSUE THREAD

**Issue by Mustang351c** [OpenMods/OpenBlocks#670]
When attempting to use a sleeping bag when a mod that prevents sleeping is installed, (Iguana Tweaks in this case) The sleeping bag doesn't allow the player to sleep  (like intended by Iguana Tweakks) but it duplicates itself every time the player tries to sleep.

**Comment by boq** [comment]
What version are you using?

**Comment by Mustang351c** [comment]
1.4.3b
Should've known I needed to include that info

**Comment by boq** [comment]
Are you sure it's Iguana Tweaks? I don't see any option like that

**Comment by Mustang351c** [comment]
It's just iguana tweaks. Not iguana tinkers tweaks. And the option is near the bottom of the config file at config/iguana tweaks/main.cfg.

**Comment by Mustang351c** [comment]
And sleeping is disabled by default I believe.

**Comment by boq** [comment]
Well, I installed [this](http://minecraft.curseforge.com/mc-mods/228798-iguana-tweaks/files), made sure `disableSleeping=true`, but I can't reproduce it. Normal chestpiece blinks in sleeping bag slot (expected) but I still end with just single copy chestpiece and sleeping bag.

**Comment by Mustang351c** [comment]
I was in creative when I was testing to see if the sleeping bag would cheat around the no sleeping. But I was right clicking with the sleeping bag in my hand instead of equipping it in my inventory if that makes a difference.

**Comment by boq** [comment]
No. Item will always be duplicated in creative, it's vanilla stuff.

**Comment by Mustang351c** [comment]
Then in that case… oops. Well thanks for clearing that up. I need to remember to do my testing in the proper game mode in the future.
