### ISSUE TITLE
[BUG] Sprinkler: water-jet duplicates

### ISSUE THREAD

**Issue by Lodugh** [OpenMods/OpenBlocks#671]
I have a bug, where the sprinkler shoots water in more than one direction. I once had it sprinkling in 3 directions. Maybe its a bug with reloading the chunk it is in or something.

**Comment by boq** [comment]
I don't really understand what you mean. Maybe screenshot?

**Comment by Lodugh** [comment]
Its just like 2 sprinklers woud be at the same place and shoot both water.

**Comment by boq** [comment]
Ok, I'm almost certain it's not possible with just OpenBlocks. Probably some tick accelerator or optifine (maybe?). Anyway, not reproducible.

**Comment by Lodugh** [comment]
Yes I have Optifine and Fastcraft installed. Sorry that I didnt mention it. And it kinda looks like the optifine update of today just fixed it. Issue can be closed I guess.
