### ISSUE TITLE
Magic crayon can be destructed in Adventure Mode

### ISSUE THREAD

**Issue by DeFazer** [OpenMods/OpenBlocks#674]
I'm putting up an adventure map heavily relying on Magic Crayon & Pencil. The issue popped up in just the first minutes of testing: even players in Adventure Mode ("gamemode 2") can easily crush drawn blocks with their bare fists. I'm using OpenBlocks-1.4.3 on MC1.7.10. Is it supposed to be like that or is it an issue?
![Drawing...](https://cloud.githubusercontent.com/assets/2264554/8846597/8fbf7e0e-3139-11e5-8191-2d65db69e2c3.png)
![...and breaking](https://cloud.githubusercontent.com/assets/2264554/8846596/8fbe31d4-3139-11e5-892a-2520eb4035e3.png)

**Comment by boq** [comment]
Just an unforeseen side effect of making this blocks 'glass'.
