### ISSUE TITLE
chunks

### ISSUE THREAD

**Issue by lightning02** [OpenMods/OpenBlocks#675]
Matierials and stuff of your mod will generate only in new chunks? Or even in old chunks of my world?

**Comment by boq** [comment]
We don't have worldgen?

**Comment by lightning02** [comment]
Neither item-loot in dungeon chest? So I can put the mod in my world without need of discover new chunks, right?

**Comment by boq** [comment]
Oh, yeah, forgot about this. There is one item than cannot be get otherwise (Technicolor Glasses), but it's not that useful.
