### ISSUE TITLE
Sky Blocks render in front of translucent objects

### ISSUE THREAD

**Issue by Platoonsgt1** [OpenMods/OpenBlocks#676]
As in the title, Sky Blocks render in front of any translucent objects between them and the player, making the translucent objects invisible. This is most notable when the translucent object is partially visible to to some Sky Block coverage behind it.

Translucent objects include: Water, Particles (Including mostly opaque ones), Stained glass and similar. Stained glass held in a player's hand is not effected.

This was using OpenBlocks 1.4.3, in the FTB Infinity Modpack 1.8.2

**Comment by boq** [comment]
Know issue. And probably unfixable. Minecraft rendering handles transparency very poorly.
