### ISSUE TITLE
Target

### ISSUE THREAD

**Issue by VallenFrostweaver** [OpenMods/OpenBlocks#685]
I am running 1.7.10-1.4.4 with only OpenBlocks installed (no other mods) through the Curse client and am getting a glitch with the Target.  When I shut it off or remove a redstone signal, the arrows I have shot in it do not fall and remain hovering in air.  I have removed the target and they still do this.  Upon first using the target the arrows DID fall but after about 5-10 minutes they stopped and will not drop at all even in new worlds.  I created a new world and won't drop. Exited, rebooted, tried a new world and they won't drop. Tried old worlds, won't drop. Tried levers, redstone torches, redstone going to a lever, still won't drop. Thought you should know.

**Comment by boq** [comment]
Please note that arrows shot from infinity bow or in creative mode are not picked. Can you reproduce that bug in creative and normal bow?

**Comment by VallenFrostweaver** [comment]
I was using a standard bow (not infinity) but I was in creative.  Thanks. I'll close the issue.
