### ISSUE TITLE
Sprinklers spread water as if it were a source block.

### ISSUE THREAD

**Issue by evil-dan2wik** [OpenMods/OpenBlocks#687]
Sprinklers will allow running water to spread as if the sprinkler were a source block.
![2015-08-13_00 24 17](https://cloud.githubusercontent.com/assets/1253226/9226384/c06774b2-4151-11e5-8259-33faa69a1267.png)
![2015-08-13_00 24 31](https://cloud.githubusercontent.com/assets/1253226/9226385/c0679e42-4151-11e5-97e5-b76f8e9feb3e.png)

**Comment by boq** [comment]
[Sprinkler IS water](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/block/BlockSprinkler.java#L16). Can't fix due to Minecraft's hacky code.
