### ISSUE TITLE
Graves only returning Baubles items and not the rest of the players inventories

### ISSUE THREAD

**Issue by NEXUS2345** [OpenMods/OpenBlocks#694]
When a player dies, graves are only returning Baubles if the player has them in their baubles slots rather than everything. So people are only getting their baubles when breaking graves. This issue is present in the latest dev builds and all the way back to release version 1.4.4.

**Comment by boq** [comment]
Graves are only storing drops that would drop normally. So I guess some other mod interferes and blocks normal drops.

Debug steps:
1. Check what drops without graves by disabling via '/gamerule openblocks:spawn_graves false'
2. If drops with and without graves differ, re-enable graves and (as op) execute command `/om_config_s set openblocks debug graves debug true`, then post all lines in log (from file, not console) that contain 'OpenMods'.

**Comment by Juniormunk** [comment]
when i type this it replies in chat unknown config value

**Comment by boq** [comment]
Sorry, extra space in there, should be "/om_config_s set openblocks debug gravesdebug true"

**Comment by mattymaats** [comment]
Hi boq,

I'm having this exact issue on the modsauce 2 pack, when someone dies it shows this in the console. 

31.10 20:24:25 [Server] INFO [20:24:25 WARN]: openblocks.common.PlayerDeathHandler.onPlayerDrops(PlayerDeathHandler.java:338): No drops from player 'EntityPlayerMP['playername'/139334, l='world', x=603.40, y=79.00, z=4241.63](playername at 603.4008419117797,79.0,4241.6320634248605), grave will not be spawned'
31.10 20:24:25 [Server] INFO [20:24:25 INFO]: playername was slain by playername
31.10 20:24:25 [Server] INFO [20:24:25 INFO]: Is a player
31.10 20:24:25 [Server] INFO [20:24:25 INFO]: openblocks.common.PlayerInventoryStore.onPlayerDeath(PlayerInventoryStore.java:303): Storing post-mortem inventory into /./world/data/inventory-playername-2015-10-31_20.24.25-death-0.dat. It can be restored with command '/ob_inventory restore playername playername-2015-10-31_20.24.25-death-0'

I have turned off OB graves with the gamemode setting and still nothing drops even on the floor. I've tried to do the om_config setting to debug to true but I can't see where the debug is output to as I'm not seeing any extra data in the console. I was looking at adding your debug mod but would I need to add that on the server as well as my client to be able to see the output or is it a serverside only mod? I know this isn't exactly a OB issue but I could really do with your help to find out what is causing graves to not function correctly as this is quite a big modpack so any help would mean a lot.

Regards,
Matt

**Comment by boq** [comment]
Logs show that something is removing all drops before grave code has chance to look at it.

If you have used `om_config_c`, then you have changed config just on your client - logs will be stored on your side. `om_config_s` is for server side and causes logs to be stored on server. Of course, if you are playing single player both work the same. Also, most output wont show in console, but in log file (in `/logs` folder).

I suggest creating local world with exact same mods and configs as server, then enable grave debug, die with items and look at logs - it should print all handlers that could change drop contents.

**Comment by boq** [comment]
There are few mods that consume drops, [like this one](https://github.com/OpenMods/OpenBlocks/issues/691#issuecomment-131939455).

**Comment by mattymaats** [comment]
Hi Boq,

Thanks for getting back to me, as this only happens when dying from another player I couldn't really test this in single player. I actually went through the plugins today and it appears to be the issue was with our combat log plugin stopping OB graves from functioning correctly. I've removed it for now but if anyone else has this occur it might be worth suggesting they check their plugins as it never used to cause an issue. Thanks for your time though the only thing I noticed was even with the debug enabled it wasn't printing anything additional to the logs only the location the .dat file is saved to.

**Comment by boq** [comment]
Uhh, I will probably add list of problematic mods at one point...

But I'm almost sure that if done correctly, there should be part of logs (in `fml-server-latest.log` or `fml-client-latest.log` or anything else loader uses) starting with `Trying to spawn grave for player`, even when grave is disabled or whole event is cancelled. Of course, it has to be set on server side and (by default) will be reverted to default after server restart.

**Comment by mattymaats** [comment]
When you do I'll be sure to add in ones I've seen issues with as we've used OB for so long now xD
It appears that plugins can also interfere with OB graves though so that is worth noting in the FAQ as a possible cause of grave problems for people.

The log was exactly the same as normal just stating the location of the DAT file so not sure what was going on there.

**Comment by vadis365** [comment]
sorry, not relevant to this mod - was showing someone this as an example of many mods' custom inventories being hard to cater for.

**Comment by boq** [comment]
Closing, since it looks like interaction with other mod, not fixable on OB side.
