### ISSUE TITLE
[v1.4.4]Block Breaker does not handle break event cancel properly

### ISSUE THREAD

**Issue by AfterWind** [OpenMods/OpenBlocks#701]
As the title says. I need this for protection checking in one of my mods. Please implement or at least consider doing so.

**Comment by boq** [comment]
I'm not sure what ancient version you have...

https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/tileentity/TileEntityBlockBreaker.java#L121

https://github.com/OpenMods/OpenModsLib/blob/master/src/main/java/openmods/fakeplayer/BreakBlockAction.java#L45

**Comment by AfterWind** [comment]
Sorry, did not specify properly. Cancelling the event does not stop the breaker to break blocks.

**Comment by boq** [comment]
Sorry, but I just tested it and I'm unable to reproduce that, at least for simple 'cancel all' handler.

**Comment by AfterWind** [comment]
Sorry, my mistake on this one.
