### ISSUE TITLE
[Suggestion] Building ability to building guide

### ISSUE THREAD

**Issue by JAWSAWN** [OpenMods/OpenBlocks#704]
A tiny suggestion that could make big differences, simply right clicking the building guide with blocks will    fill the guided areas and consume the blocks from the player's inventory.
Or it could be more automation based with placing a hopper connected to guide and putting items into it. 
If the blockspace is already filled, the guide wont replace nor place blocks into those spaces.

**Comment by nevercast** [comment]
In creative, place an obsidian block on the top, then right-click with an item. 
These conditions must be met though:
* You must be in creative
* You must have an obsidian block above it

**Comment by nevercast** [comment]
I'm aware that you intend this to be available to all players in survival. 
My opinion is that is OP. 

Please use this comment section to discuss why you think the current option is not a sufficient solution.

**Comment by boq** [comment]
Hey, I was actually going to implement that one. Click with ItemBlock on guide -> place it in next free space, consume item (shift-click to use whole stack?). Nothing more OP that existing solutions in other mods. Unless you are comparing it with stuff like Builcraft filler? Maybe we can consume XP and/or hunger (!)?

**Comment by nevercast** [comment]
I think consuming XP is a good balance. 
OB is becoming more and more like a techmod. I'm happy with that because we use XP as our fuel.

Maybe the cannon should consume XP in the future too. Perhaps by default config to not break current systems. With the latest update that's more OP than the build guide (Tested to launch blocks 800 meters with chunk loaders)

Yup. If it consumes XP that sounds good boq. Enjoy :D

**Comment by boq** [comment]
I'm leaning towards hunger-cost - auto-placing would be replacement for going to marker and placing block, so hunger (and time) are normal cost.

And with XP there is always risk it will cause same problems as elevator (look at all those 'elevator not working' reports).

**Comment by nevercast** [comment]
A chat message of "You are out of XP" or "Insufficient XP levels to use this" would probably mitigate that.

**Comment by nevercast** [comment]
The upside to hunger is that it can't easily be produced in techpacks. Unlike XP.

**Comment by JAWSAWN** [comment]
I think right clicking in survival, block by block is not that op. You only click fast as you can place a block. Like how blood magic uses its rune placement. Forget the hopper system, its op.
