### ISSUE TITLE
Crash - Invalid Shapeless Recipe

### ISSUE THREAD

**Issue by JasonMcRay** [OpenMods/OpenBlocks#705]
I just downloaded OpenBlocks-1.7.10-1.4.4-snapshot-664 and I was greeted with this crash: http://pastebin.com/RH8ih2SD

note: I have Elevators disabled in my configs. When I disable also the Elevator Rotating in the config -  crash no longer occurs.

I understand it is because Elecator rotating is dependant on normal Elevator. But maybe in future if the Elevator is disabled, then automaticaly disable the rotating one (if possible)

**Comment by boq** [comment]
That was typo in already existing check. Elevators will stay separate in config.
