### ISSUE TITLE
Crash in Creative Mode with Flag Item disabled

### ISSUE THREAD

**Issue by Reidsb** [OpenMods/OpenBlocks#706]
Not sure it's this mod, or Forge, or vanilla Minecraft causing this, but if you have the Flag Item disabled, and are in creative mode and try to tab over to the screen with the mod-added items, the game crashes. Presumably because the Flag is the icon for the mod on that screen, and it can't find an image to put there.

Maybe a heads up in the configs so people are aware? Took me a bit of troubleshooting to realize what the issue was.

I'm running Mystcraft and Thaumcraft on my server in addition if that matters. Re-enabling the Flag Item stopped the crash, luckily.

**Comment by boq** [comment]
Please, always post crashlog. OpenBlocks already handles this case (flag icon should be replaced with vanilla's sponge), so I have no idea what actually crashes.

**Comment by boq** [comment]
Closing due to lack of response.
