### ISSUE TITLE
Since 1.6, elevator blocks center player after a teleportation

### ISSUE THREAD

**Issue by ExDomino** [OpenMods/OpenBlocks#707]
In 1.5.2, when we're using elevator blocks disposed on 2x2, the x,y location was not changed after the teleportation, but in 1.6+, x,y are changed to place the player at the center of the elevator block that was used. Is there a way to disable this feature? It's a little bit irritating. Thanks in advance! ^^

**Comment by boq** [comment]
![obligatory XKCD](http://imgs.xkcd.com/comics/workflow.png)

Ok, explain why you need it and I may add this as an option.

**Comment by ExDomino** [comment]
When you create an elevator, I mean by design, a room with 2x2 or 3x3 elevator blocks (yes I know it's expansive because it costs from 4 to 9 ender pearls and 8x more of wool, and 4 reapparing blocks as door per floor, but that's not the point) you lost in immersion when you go up or go down to the next or previous floor when you get centered on the block that teleported you. It's not a major issue but since 1.5.2 it looks like a kind of "bug" to me, because I was used of the old behavior.
