### ISSUE TITLE
OpenBlocks 1.4.4

### ISSUE THREAD

**Issue by ReneMuetti** [OpenMods/OpenBlocks#708]
Hello
I woltle today use the building guide for the first time. Unfortunately it does not display preview of the blocks. I watched the tutorial video, where they are displayed. In the log file any errors are identified. Can you fix it?

Many thanks

**Comment by boq** [comment]
Not a bug, please check [FAQ](http://openmods.info/faq.html#ob-8). Video is outdated.

**Comment by ReneMuetti** [comment]
okay -- Thanky for Help :)
I'll add it time in German translation :)
