### ISSUE TITLE
Another one dupe

### ISSUE THREAD

**Issue by zHawky** [OpenMods/OpenBlocks#714]
Possible to dupe filled tanks when keep in hand more than one(after refresh inventory). 
Railcraft 9.7.0.0
OpenBlocks 1.4.4
Inventory Tweaks 1.58
Forge 1448

**Comment by boq** [comment]
What is "inventory refresh"? Please provide all steps needed to reproduce.

**Comment by zHawky** [comment]
Refresh inventory mean press r for sorting inventory, that is Inventory Tweaks mod.
Im make coke oven, then try to extract directly from oven with tank, he dissappear, then refresh or right click on the oven he return my dublicate of tank but filled.

**Comment by YuRaNnNzZZ** [comment]
This bug can be replicated with right clicking with OpenBlocks tanks on RC tanks to exrtract fluid.
@boq, here is steps to reproduce:
1. Take 2-64 OpenBlocks tanks in hand.
2. Right click with it on RC tank/coke oven/other RC block with fluid in it.
3. Duped tanks are invisible in your inventory - just click any slot and you will see it.

**Comment by YuRaNnNzZZ** [comment]
Edit: any slot will not work, so you need relog to server/singleplayer

**Comment by boq** [comment]
I have a feeling that it was reported somewhere, but I can't find it. Maybe it was IRC only.

Anyway, if it's CovertJaguar/Railcraft#625, then:
- shadow tanks should be in first empty slot
- it's not OpenBlocks bug

**Comment by zHawky** [comment]
YuRaNnNzZZ thanks for better explain my problem ;)
My grammar is terrible..
So if not OP problem then closing.
