### ISSUE TITLE
no gravestone after death

### ISSUE THREAD

**Issue by SDUBZ** [OpenMods/OpenBlocks#718]
i died on top of wheat farm and re-spawned no grave in any direction of death and the restore inventory didn't even restore items back either rip all that time levelling all those tinkers tools can you please fix this bug so it doesn't happen to others like it did to me the version im using is as follows OpenBlocks-1.7.10-1.4.4

**Comment by zHawky** [comment]
Dude graves working for me, check configs maybe you disabled him

**Comment by boq** [comment]
Please follow procedure described here: http://openmods.info/faq.html#expand-ob-0

**Comment by boq** [comment]
Closing due to lack of response. If you still have this problem, please create new report after following steps from FAQ.
