### ISSUE TITLE
[Suggestion] Disguiseable Elevators

### ISSUE THREAD

**Issue by Gebcrafter** [OpenMods/OpenBlocks#719]
I am building a Savannah Mansion, and i have an elevator which looks not-so-great when the floor is default elevator texture. It would be incredibly amazing if i could make the elevators look like different blocks. Take a gander;
![2015-10-18_13 08 09](https://github-cloud.s3.amazonaws.com/assets/15183529/10565227/a8e41f6c-7599-11e5-8e95-5dd8d9f79e6d.png)
![2015-10-18_13 08 46](https://github-cloud.s3.amazonaws.com/assets/15183529/10565228/ace97db4-7599-11e5-8293-e578793c86ac.png)

**Comment by InjuredWolf** [comment]
does the EIO painter work?

**Comment by ryantheleach** [comment]
Seeing this just gave me an idea of having my entire base floor made of elevators.

**Comment by boq** [comment]
Only 2 years late: `dropblock.overrides` - config option to add elevator functionality to any blocks. Available in 1.7.3.
