### ISSUE TITLE
openmods.geometry.BlockTextureTransform.<init>(Lnet/minecraftforge/common/util/ForgeDirection;)V

### ISSUE THREAD

**Issue by Tsyklop** [OpenMods/OpenBlocks#722]
Crash http://pastebin.com/ahjsbYed

laset wersions from Jenkins

**Comment by boq** [comment]
Expected. Please don't use snapshots unless you really need, because there is no guarantee it will work.

**Comment by Tsyklop** [comment]
OpenBlocks-1.7.10-1.4.4-snapshot-670 and OpenModsLib-1.7.10-0.8-snapshot-398 works.
