### ISSUE TITLE
[Enhancement] Multi-block tanks should report total capacity instead of per block capacity

### ISSUE THREAD

**Issue by mikeloeven** [OpenMods/OpenBlocks#725]
So i ran into an issue working with open block tanks while the tank it's self was 3x3x3 and had a total capacity of 432000 each tank reports 16000 out of 16000 dispite being a multiblock. This causes issues with mods that automatically supply fluids such as Logistics pipes in that it sees the tank as full as soon as the tank touching the supplier is full regardless of weather or not there are empty tanks above it. Generally speaking you should make multiblock tanks report the multiblocks total capacity and only revert to their default capacity when removed from the multiblock

**Comment by boq** [comment]
They are not multiblocks. They just have connected texture and automatic balancing with direct neighbours.
