### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by JasonMcRay** [OpenMods/OpenBlocks#726]
Crash: https://paste.ee/p/4AZOU

Crash happens when I log into my world. Was fine with OB 677 and OML 402
New world is fine

OpenBlocks-1.7.10-1.4.4-snapshot-683
OpenModsLib-1.7.10-0.8-snapshot-412

**Comment by boq** [comment]
Ok, will fix. But please don't use snapshots in modpacks.

**Comment by boq** [comment]
Fixed in OpenModsLib.
