### ISSUE TITLE
/dev/null is not picking up blocks that are dropped on the floor

### ISSUE THREAD

**Issue by WalaoEgg0424** [OpenMods/OpenBlocks#729]
Someone has post a issue on a modpack github says that he notice that /dev/null didnt pick up those blocks that are dropped on the floor. Instead of /dev/null picking it up , the dropped block goes into his inventory. There is no crash log.

**Comment by boq** [comment]
Sorry, can't reproduce this one. It may be possible, that some other mod modifies items once dropped.

**Comment by helium2s1** [comment]
Having the same issue in the Space astronomy modpack. All functionality expect picking up blocks (which also affects the voiding of blocks) works. Since you suggest that it's mod interaction, I'll report this to the modpack author, as well.

**Comment by WalaoEgg0424** [comment]
I already told the modpack author. Sorry that i forgot to says that this is Space Astronomy modpack.

**Comment by boq** [comment]
There you go:
https://github.com/SteveKunG/More-Planets/blob/master/src/main/java/stevekung/mods/moreplanets/core/event/MorePlanetEvents.java#L389

Mod should've used PlayerEvent.ItemPickupEvent which is called after item is picked, and not force early pickup.
