### ISSUE TITLE
Skyblock/ Inverted Skyblock

### ISSUE THREAD

**Issue by Theotherguy1223** [OpenMods/OpenBlocks#730]
I used to use these in previous versions and they were great, but in 1.7.10, now they don't seem to show the sky at all, now they just show blue and black with fades, not even the color of the sky in the biome I'm in, I'm just wondering if this is intentional or not? it seems weird to take away such a great feature.

**Comment by boq** [comment]
You mean different from MC 1.6? Only method of rendering changed, end effect is still the same (that was forced by similar changes in Minecraft/Forge).

There are two possibilities:
- some other mod interacts with rendering
- you have GPU with poor OpenGL support (i,e, Intel).

**Comment by Theotherguy1223** [comment]
I can confirm that this is the issue, I created a new instance with only open blocks, forge and open mod core, and it works fine, any Idea how to find the mod responsible, or how to fix it?

**Comment by boq** [comment]
Uh, no idea. Can you trigger crash by holding F3+C ingame for few seconds and then post crashlog here?

**Comment by Theotherguy1223** [comment]
Modded Minecraft takes too long to start

Log:
http://pastebin.com/XaTUX0pR

**Comment by boq** [comment]
Standard first guess: Optifine.

Also, are you using any launcher? It's not a problem in itself, but I see some non-standard settings.

**Comment by Theotherguy1223** [comment]
I was kinda figuring it was Optifine, but wasn't sure.

Yea, using MultiMC

**Comment by Theotherguy1223** [comment]
probably should have asked, but any way to fix it without removing optifine?

**Comment by boq** [comment]
Sorry, but no. Optifine does weird, undocumented things. 

Have you even wondered, why those two lines are in you crashlog?
```
Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client:
Optifine
```

Yeah, it's that bad.

**Comment by Theotherguy1223** [comment]
oh well, FastCraft is a good enough performance mod that I guess I don't need Optifine

**Comment by Theotherguy1223** [comment]
Nope, removed optifine, issue persists

**Comment by boq** [comment]
Then maybe try this:
- get Total Commander
- go to mods folder
- open search dialog (alf+f7)
- check "search archives"
- type `*.class` in "search for"
- check "find text"
- type "glStencilFunc" in box next to it
- "start search"
- look at found jar files

Or just use any other tool that allows you to search through contents of compressed files.

**Comment by Theotherguy1223** [comment]
will do that when I get home tonight, but not sure if it will help, Log without Optifine:
http://pastebin.com/bW6EAzrv

And pictures of the issue at hand:
![pic 1](http://puu.sh/lQM8q/5d491e0716.png) ![pic 2](http://puu.sh/lQM7N/40d207a114.png)

Both pictures taken seconds apart, at the same spot, second picture is 20 block lower, underground with the Inverted Sky blocks

**Comment by boq** [comment]
Yeah, that's how it's supposed to look when rendering is broken - it's "fog" color.

**Comment by Theotherguy1223** [comment]
Found Jar Mods are:
CodeChickenCore-1.7.10-1.0.7.47-universal.jar/codechicken\core\GuiModListScroll.class
CoFHCore-[1.7.10]3.0.0RC7-211.jar/cofh\lib\gui\element\ElementBase.class
OpenModsLib-1.7.10-0.6.jar/openmods\renderer\StenciledTextureRenderer.class

**Comment by boq** [comment]
Then I have no idea...

**Comment by Theotherguy1223** [comment]
Guess I'll backup and try uninstalling mods one by one, then let you know what it was

**Comment by Theotherguy1223** [comment]
Found it, The problem is CoFHcore removing that fixes it, and putting the mod back in, repeats the issue

**Comment by Theotherguy1223** [comment]
FIX: Updating to the latest Version of CoFHCore fixes the issue
