### ISSUE TITLE
[Suggestion] Config option for fans pushing through blocks

### ISSUE THREAD

**Issue by rob5251** [OpenMods/OpenBlocks#735]
It would be nice if there was a way to disable the fact that fans can push entities around even when blocks are in front of the fan.

This can make it difficult to work around them; it would be nice if you could hide behind a block and not get pushed by the force its producing.

This could be a config option or just disable it altogether as it seems like rather odd behavior.

**Comment by boq** [comment]
That would significantly increase server loads. - for example: if you have mob farm with row of 5 fans and about 50 mobs inside, this will cause 5*50  = 250 raytraces per tick (5000 raytraces per second), and single raytrace is already heavy operation.

**Comment by rob5251** [comment]
Ah ok, I wasn't sure of the reasoning behind it.
