### ISSUE TITLE
Issue with /dev/null

### ISSUE THREAD

**Issue by axle2005** [OpenMods/OpenBlocks#736]
Openblocks 1.7.10-1.4.4

SMP Duplication Issue on FTB Infinity 2.2.2

Old Issue: <a href="https://github.com/OpenMods/OpenBlocks/issues/684">684</a>

Same method mentioned in old issue now causes a duplication of the /dev/null and contents.

**Comment by boq** [comment]
It is the same issue, it was fixed after 1.4.4 was released.
