### ISSUE TITLE
Sprinkler is infinite and ability to turn off

### ISSUE THREAD

**Issue by Zyles** [OpenMods/OpenBlocks#737]
So I was testing sprinklers in creative and it seems one bucket of water can run the sprinkler for I don't know how long. Is it infinite, or what is the duration?

Also a way to turn off the sprinkler would be nice.

I want to only water at night, so I made a system that did this (quite the setup), but then I noticed they never run out so it keeps running for several days which made me hugely disappointed.

I tested with both a fluid tank from EnderIO and a raintank from Forestry underneath and they were both empty.  It probably would be more balanced if one bucket = one day. Or simply disable the sprinkler when the water container beneath is empty? It is weird that it keeps going with no water source.

Thanks.

**Comment by boq** [comment]
Numbers are unchanged since beginning: sprinkler uses 1 mB every 60 ticks (3 real-world seconds), so with 23000 ticks/in-game day that makes 400 mB daily. Sprinkler also has internal buffer of 1000 mB.

I can add config options for this values and maybe even tweak it little bit. But I'm not sure how people are using it...

**Comment by Zyles** [comment]
From what I have seen on the server I play, tutorials on internet etc. and how I use it. People use a tank of sorts below the sprinkler 99% of the time since it has no input and wont connect to pipes.

To me the internal storage seems redundant and unrealistic, it is a sprinkler basically and shouldn't store anything. But that may be my opinion. For me it would be most convenient if it took the container contents and if it's empty it doesn't sprinkle. That makes it very simple to use, understand and easy to turn off. If you would have to put redstone at the same level as the sprinkler to turn it off it would ruin most farms.

So my suggestions:

1. Only sprinkle if the container below it contains water (most preferably)
2. Or be able to turn it off with redstone at 2 blocks below (because of container in the way) but that redstone signal may also affect the container if it allows redstone
