### ISSUE TITLE
[Bug] OpenMods not found

### ISSUE THREAD

**Issue by RaiderofRamen** [OpenMods/OpenBlocks#739]
Whenever I try to open Minecraft with OpenBlocks v1.5 and OpenModsLib v0.9, the following error comes up:

"Forge Mod Loader has found a problem with your minecraft installation
The mods and versions listed below could not be found
OpenMods : [0.8,0.9)
The file 'logs/fml-client-latest.log' contains more information"

Log file: http://pastebin.com/WK75Yaig

**Comment by boq** [comment]
You still have OpenPeripheral-1.7.10-AIO-5.jar. It requires previous version of OpenModsLib.
