### ISSUE TITLE
Dupe bug with Sync, OpenBlocks, and Tinker's construct

### ISSUE THREAD

**Issue by MJRLegends** [OpenMods/OpenBlocks#741]
Not sure if anything can be done from your side for this but see MJRLegends/Space-Astronomy-Feedback-#169

**Comment by Blue64** [comment]
[My idea](https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/169#issuecomment-169701896) for a fix.

**Comment by boq** [comment]
Nothing to do on our side - you die, you drop items, grave captures it. It's up to other mods to cancel/modify/work around that event.

**Comment by MJRLegends** [comment]
@boq well the developer of the sync mod doesnt update his mod anymore, is there a way you can make a workaround to make it work?

**Comment by boq** [comment]
Sorry, but no. We have no way of knowing source of drops, so no filtering is possible.

**Comment by MJRLegends** [comment]
Ok no worries
