### ISSUE TITLE
Issue with building guide.

### ISSUE THREAD

**Issue by DeadlyForest** [OpenMods/OpenBlocks#742]
The "Ghost" blocks that are meant to help are not showing up, particles are enabled. I place it down and it kinda just sits there and does nothing. I will include screenshots.
![2016-01-03_21 08 19](https://cloud.githubusercontent.com/assets/16531704/12082281/40ef9f6a-b25e-11e5-818a-237d292cabfd.png)
![2016-01-03_21 08 28](https://cloud.githubusercontent.com/assets/16531704/12082282/41069cf6-b25e-11e5-8aa5-27d453e38389.png)
![2016-01-03_21 08 41](https://cloud.githubusercontent.com/assets/16531704/12082283/411c4290-b25e-11e5-96e0-7636dbb318ea.png)

**Comment by TheSilkMiner** [comment]
> Since version 1.3 [the Building Guide] needs redstone power to work.
> This behavior can be configured with `guide.redstoneSensitivity` configuration option.

Source: [FAQ](https://openmods.info/faq.html#expand-ob-8), under `Why doesn't building guide show any markers?`

**Comment by boq** [comment]
Closing.

@TheSilkMiner: thank you for responding.
