### ISSUE TITLE
XP Shower breaks on block update

### ISSUE THREAD

**Issue by xypista** [OpenMods/OpenBlocks#743]
The XP Shower breaks on block update if it is connected to some tile entities.

I observed this with ExUt Drum, BC Tank, TE Portable Tank and even on some non liquid containers suck as vanilla chests, AE Terminals (altough why would anyone put it on those).

**Comment by boq** [comment]
Hmm, this is tricky one. Shower is coded to break when it finds it's attached to "non-solid" wall (which is just attribute on block). Actual bug is that it isn't supposed to placeable on non-solid walls in first place, but fixing that would severely limit usability.
