### ISSUE TITLE
Last stand enchant on armour worn by mobs

### ISSUE THREAD

**Issue by Bennyboy1695** [OpenMods/OpenBlocks#744]
I have recently discovered that any mob that has a piece of armor with the last stand enchant on it, will be invincible and unable to kill. THis causes a lot of issues when you have no way of killing it, only way i have found to remove the mob is to pick it up with a minefactoryreloaded safari net that's thrown by a launcher or to kill all mobs using a command .

Proof can be found here: http://goo.gl/IVxAWJ (Shows my playerdata of the safarinet containing the zombie with last stand enchant
 Proof of id 212 being last stand: http://goo.gl/wsyPnN (Nei dump of enchants)

**Comment by boq** [comment]
Last Stand works ONLY on players. 
What's interesting is `AbsorptionAmount` - it's about 12 extra hearts (Absorption VI potion).

**Comment by Bennyboy1695** [comment]
Could it be a bug ? Meant to only work on players, but possible that because the zombie has no xp the last stand makes him un-damageable ?
All the other enchants he had on his armour were vanilla enchants and he didnt have any potion effects that i could see so last stand was the only conclusion i could come to

**Comment by boq** [comment]
It simply won't work on anything else than player: https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/enchantments/LastStandEnchantmentsHandler.java#L19.

**Comment by boq** [comment]
Closing, since there is no information and it's probably not our bug.
