### ISSUE TITLE
Server crash - cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Lopenblocks/common/item/ItemCartographer;

### ISSUE THREAD

**Issue by ProsperCraft** [OpenMods/OpenBlocks#745]
http://pastebin.com/NBCUMTjm

**Comment by ProsperCraft** [comment]
This crash occurs right after the server starts every time.

I disabled the mod and started the server which wiped some blocks from the map, but when re-enabling the mod it crashed on load again.

**Comment by boq** [comment]
Can't reproduce this on fresh install of modpack. Please run with `-Dlegacy.debugClassLoading=true` appended to JVM arguments.

**Comment by ProsperCraft** [comment]
It is no longer crashing, it must have been disabled long enough to wipe the erroring item, I will post more info if it starts again.

**Comment by boq** [comment]
It wasn't single item. Other mod did something weird and was crashing game before world has loaded.
