### ISSUE TITLE
Client crash "World Domination with Openblocks" book.

### ISSUE THREAD

**Issue by DrWookie** [OpenMods/OpenBlocks#746]
Client crashes with render error while reading "World Domination with Openblocks" book.

running:
OpenBlocks-1.7.10-1.5.jar
OpenModsLib-1.7.10-0.9.jar

crash log:
http://pastebin.com/PLawCbjn

**Comment by boq** [comment]
Fixed in OpenMods/OpenModsLib@39d37b0.

Note: it looks like newer versions of Forestry just show default "missing block" instead of crashing.
