### ISSUE TITLE
Elevator Config

### ISSUE THREAD

**Issue by Gowcu** [OpenMods/OpenBlocks#750]
this may not be an issue, but i am trying to config the elevator to pass through water blocks with the following config {minecraft:water:ignore} and am unable to get it to work. is this a bug or am i just imputing the config edit wrong.

**Comment by boq** [comment]
```
    S:specialBlockRules <
        "minecraft:water:ignore"
     >
``` works fine.

Please note that this is config for still water, but water also has other block called `flowing_water`
