### ISSUE TITLE
Broken Textures

### ISSUE THREAD

**Issue by Doublechest** [OpenMods/OpenBlocks#752]
My Openblocks Textures don't show. I'm using Openblocks in a Modpack. 
Other Mods: 
Mo Pickaxes, RPGLoot, Treecapitator, Lucky Block, Nevermine 2, Ancient Warfare, Backpacks, Bibliocraft, Dmg. Indicators, Rotten Flesh > Leather, Hats, Morph, Mr Crayfish Furniture, NEI, Orespawn, Portal Gun, Roguelike Dungeons, TConstruct, Vein miner and xaeros minimap
and of course everything the mods require
If Openblocks isn't compatible with one or multiple of these mods please tell me
(openmodslib is installed)
All mods work except for Openblocks

**Comment by boq** [comment]
Please be more precise. What textures are you talking about? Blocks, items, entities or GUIs? Are they built-in textures or custom resource pack? And what do you mean by "don't show"? Checkerboard pattern or something else?

Also, there are no known incompatibilities. We also don't do anything weird with texture loading.

**Comment by Doublechest** [comment]
i mean none of the textures don't show (checkerboard pattern) and i have no custom resource pack installed

**Comment by Doublechest** [comment]
none of the textures show*

**Comment by boq** [comment]
Are you using 1.8 snapshot?

**Comment by Doublechest** [comment]
no i'm using 1.7.10

**Comment by boq** [comment]
Uh, so I have no idea. As I said, we don't do anything special with textures loading.

Redownload mods and post full log.

**Comment by Doublechest** [comment]
It worked after redownloading it! :D Thanks for the help
