### ISSUE TITLE
Grave spawns on 0th block layer if player died in void

### ISSUE THREAD

**Issue by Technus** [OpenMods/OpenBlocks#754]
Suggested fix: check if spawn location is below 5th layer then move to 6th layer.

Afaik, added the solution in fork.

https://github.com/GTNewHorizons/OpenBlocks/blob/master/src/main/java/openblocks/api/GraveSpawnEvent.java

**Comment by boq** [comment]
Should be fixed by 767b3f2c44d5972fc394f7deb97b565d51dacd40.
