### ISSUE TITLE
Building Guide can't be rotated on Pentagon and Triangle

### ISSUE THREAD

**Issue by chaos234** [OpenMods/OpenBlocks#757]
The title of this error says all.

I need a rotation option but I can't find out why it's not rotating if I replace it from another direction (e. g. first placed looking to the north, after that, replacing it but looking to the south direction).

So I think that this is an error and I hope that it will be fixed soon other wise it has to be implemented because how should a player then be able to buld a magical pentagram as design element.

Also your drawing methode for the pentagon is false because it looks like a bowl with cornflakes but not like a pentagon. The error are the top two corners which are not corners.

The drawing methode for the pentagon should be made from triangles. One ro the top and another one mirrored to get the next two corners, after that simple draw a line at the correct position and you have a correctly drawn pentagon.

**Comment by boq** [comment]
How about using those two arrows on top? https://www.youtube.com/watch?v=zUf_p8zvovM 

Or maybe using any wrench-like tool (we have Big Metal Bar for that purpose).

**Comment by chaos234** [comment]
OB does not have such a Building Guide. It has only this one: https://www.youtube.com/watch?v=DV4MU38ogWs

NEI shows also only this Building Guide and not another one. Also I can't and do an update.

**Comment by boq** [comment]
As I have expected, you have old version. NOT SUPPORTED.
