### ISSUE TITLE
[Suggestion] Vacuum Hopper Hitbox

### ISSUE THREAD

**Issue by Galaxia-neptuna** [OpenMods/OpenBlocks#758]
The Vacuum Hopper, despite being small, have a full block size hitbox. Sometimes when I want to open a chest located beside a vacuum hopper, I accidentally click the vacuum hopper because it looks smaller than the hitbox size, and it's quite annoying. It would be great if you could size down its hitbox so that it doesn't take up the full block.

**Comment by boq** [comment]
Fun fact: looks like it was supposed to be that way from very start, but initial implementation was derped.
