### ISSUE TITLE
Crash when activating inventories remotely

### ISSUE THREAD

**Issue by GodsVictory** [OpenMods/OpenBlocks#760]
Crashed caused when activating a GUI from long distances

This particular instance was caused when activating a Storage Core from EZStorage, however, I have tested numerous blocks with the same issue, such as EnderIO Inventory Panels and Progressive Automation Machines.

http://pastebin.com/raw/FzWxZFCN

**Comment by boq** [comment]
Well, I couldn't reproduce it, but I'm limiting interaction to lowest hard limit I count find.

**Comment by GodsVictory** [comment]
I couldn't get it to work with any vanilla minecraft blocks. Only added mod blocks. If you tried with EZStorage of EnderIO, make sure you are in creative mode. Make sure the chunk stays loaded by the storage core/inventory panel, and activate the cursor on it. Then fly far out and try to activate it. On 1.7.10 it will crash, on 1.8.9 it will cause errors in the log without a crash.
