### ISSUE TITLE
/dev/null any item duplication

### ISSUE THREAD

**Issue by MagicalMechanic** [OpenMods/OpenBlocks#765]
This Dupe is done with a /Dev/Null. First, you put the item (or bags/chests of items) you want to dupe in a /Dev/Null while the /dev/null is in the first slot. Then you place any item into another hotbar slot, (I used slot 4), then you open the /dev/null while pressing the number on you keyboard that corresponds with the hotbar number (again, i used 4). You will know you did it correctly if you hand shows the other hotbar item while you have the /dev/null inventory open. While the /dev/null inventory is open, move the /dev/null in your hotbar to another hotbar slot, once moved, you can remove your item. then once you close the /dev/null inventory, another /dev/null will appear in the first slot of your hotbar with the new items.

How they explained it:
http://puu.sh/o1E75/e1285dea84.png

Before 1:
http://puu.sh/o1Du1/632ea61d02.png

After 1:
http://puu.sh/o1DvR/331791a7ff.png

Before 2:
http://puu.sh/o1DiS/a6e6fde043.png

After 2:
http://puu.sh/o1DkY/ac72d2b95c.png

**Comment by runescapejon** [comment]
@boq this is still an issue,

this is how to dupe basically bypassing your fix

1) you put any item in the /dev/null
2)  (this is the trick) you quickly Drop the item at the Same Shift rightclick (open the gui) 
3) get the item out of the gui, then you pick up the item you drop  and get the item out of that 
So you would have dupe 2 /dev/null and the item you wish to dupe with

**Comment by boq** [comment]
I can't reproduce this by holding shift and then right-clicking and dropping with 'q'. Did you mean something else?

Also, please post exact versions used.

**Comment by boq** [comment]
Pushed fix for OpenModsLib ([build](https://builds.openmods.info/job/OpenModsLib/465/)), should be enough to fix that (and possibly some simpler methods).
