### ISSUE TITLE
[BUG] XP Dupe Bug with Runic Dungeons Ring O' Experience

### ISSUE THREAD

**Issue by DutchPlays** [OpenMods/OpenBlocks#771]
The Runic Dungeons Ring O' Experience absorbs nearby XP, but when using the Ring with an XP Shower, the amount of XP that you get is about 8x more than you're supposed to get, even though it uses the same amount of Liquid XP.

**Comment by boq** [comment]
Probably missing check for `isDead` in ring code. Also, it seems ring was removed in Runic Dungeons v1.1.6c, probably due to MrComputerGhost/Runic-Dungeons#13.
