### ISSUE TITLE
sprinkler duplicate.

### ISSUE THREAD

**Issue by BartolomeoDR** [OpenMods/OpenBlocks#773]
Hi. I found this duplicate glitch on 1.6.4 and now I test it on 1.7.10
Yeah! it`s working! 

1) put sprinkler 
2) pour any liquid  (excluding water and lava) also any liquids in mods
3) have х2 sprinkler

You can watch my video 
https://youtu.be/xi9Ow3LGvaA?t=2m20s

**Comment by boq** [comment]
I'm not sure what ancient version you have, but it's not reproducible in most recent OpenBlocks (for 1.7.10). MC 1.6.4 is, of course, completely unsupported,

**Comment by fhntv24** [comment]
Sorry, but you are wrong. You have fixed it with lava&water, but some fluids still do dupe.
Problem is yours - you are using Material.water, and this is wrong for actuall blocks.
Some fluids "override" Material.water by flowing into it, and they will call breakBlock ( or how its called, i cant remember ) *TWICE*. Yes, this is bug, but its vanilla bug. So you could fix vanilla code, that each mod uses, or you could change material to somethnig else.

And again - yes it doesnt work with all fluids, but some - do dupe. 
(Tried in latest version that is aviliable on openblocks web site)

**Comment by boq** [comment]
Ok, then issue description is misleading - I tried BC oil and fuel and BM
life essence and couldn't break sprinkler, so I'm assuming at least Forge
standard fluid works.

**Comment by boq** [comment]
Also, it's water since there is no hook for 'provides moisture' in
farmland. Should've been PRed some time ago, but...

**Comment by fhntv24** [comment]
Just tested with fluid from Biomes'O'Plenty and thaumcraft - they both will dupe. Also all FINITE fluids ( FiniteFluid class ) will wash sprinkler, but it wont dupe. All other fluids just wont wash sprinkler at all. I think open blocks + BOP / Thaumcraft is pretty popular combination. And yes, it doesnt work with a lot of mods - but in same time it works with a lot of other mods.

**Comment by UndeadZeratul** [comment]
if it's a specific set of fluids, wouldn't that mean that those fluids are the cause, not the blocks or the base fluid classes?

**Comment by fhntv24** [comment]
Its actually bug in BlockFluidClassic, and this is why some fluids dont work and some do.

**Comment by boq** [comment]
Well, now that I have enough info to reproduce, I may at least try to
prevent double drop. I don't care about block breaking.

**Comment by fhntv24** [comment]
@boq you could change metadata / check if block is air before droping and set it to air after first break, that might help.

**Comment by boq** [comment]
Well, drops in 1.7.10 are needlessly complicated, so simple solution
probably won't cover all cases.

**Comment by boq** [comment]
Ok, I have found the solution to double drops. Will commit later (internet problems).

**Comment by BartolomeoDR** [comment]
YEAH ! I WIN!  I know a lot of duplicate glitch on your mod.

**Comment by boq** [comment]
Well, your issue would be dead and forgotten, if somebody else wouldn't step in and clarify what "any liquid" means (hint: not any liquid). So I wouldn't call it "win".

Also, whole point of issue tracker is, well, reporting issues. Not gloating about knowing them.
