### ISSUE TITLE
Possible Grave Issue [Query]

### ISSUE THREAD

**Issue by CobaltSparkz** [OpenMods/OpenBlocks#775]
Hey there,

I've noticed that a lot of people are having some items restored, or just baubles, or sometimes nothing in the grave. I've read all the wikis and looked through my mods and plugins, but I can't think of anything off the top of my head that would cause issues.

I've turned of gamrule keepInventory, and used the grave spawning: true gamerule or whathaveyou, so the issue isn't that graves aren't spawning, more the contents of the graves vary, greatly.

Here's a pastebin containing the debug dump on a random grave creation.

http://pastebin.com/eyGGzz8N

Many thanks

Sparky

**Comment by boq** [comment]
Well, at this point I can only say: grave contains items that would drop normally - if they aren't in grave, they probably wouldn't drop at all.

There are some issues with mods removing specific items, destroying all items or making general mess due to subtle bugs. But it's almost impossible to debug in modpacks - in your case there are over 50 pieces of code that can possibly modify drops.

**Comment by Eufranio** [comment]
Are you using KCauldron?

**Comment by CobaltSparkz** [comment]
Hey, sorry for the long response. I am using a fork of KCauldron, yes - I am running the Resonant Rise: Mainline pack, so there are a LOT of mods in there. Was just on the off chance you could isolate something specific, not to worry. 

Thanks

Sparky

**Comment by boq** [comment]
Ok, to make debugging easier, I made this https://github.com/boq/DropDebug/releases/tag/v0.1. This will log what drops are removed, added or modified by which listener - should be able to identify where items disappear.

Probably buggy as hell, but seems to work in basic case. Just type `/debug_drops install` in chat to activate, and look for `[DebugDrops]` in logs after every death. `/debug_drops uninstall` to deactivate. Warning: spammy as hell.

**Comment by CobaltSparkz** [comment]
Much appreciated, Boq, I'll give this a go and circle back with results, if that's ok?

**Comment by boq** [comment]
Any luck with this tool?

**Comment by Frostthejack** [comment]
This crashes on single player the debug tool that is

**Comment by boq** [comment]
You have used development version (-deobf). Please use other JAR file.

**Comment by Frostthejack** [comment]
ah ok tyvm

**Comment by CobaltSparkz** [comment]
Hey, my apologies for not getting back to you - It appears the issue, for the most part, was a setting in GriefPreventionPlus, which was not allowing drops from PvP deaths, that seems to have resolved it. We're still having the issue on some servers in the End, which I believe to be Hardcore Ender Expansion interfering, some how

**Comment by boq** [comment]
OK, thank you for information. I will probably expand mod list in FAQ at one point.

Also: closing this issue.
