### ISSUE TITLE
Last Stand nerfs

### ISSUE THREAD

**Issue by Flenix** [OpenMods/OpenBlocks#784]
Hey,

We discussed some ideas for Last Stand nerfs on IRC a little while ago, just a nudge to remind you :)

Issue was that players were storing XP then if they go to a dangerous area or go on a raid, they'd fill up and often have 100+ levels making them almost totally impossible to kill. You had some good ideas for a fix; something about using a calculation so if they're over level X it consumes more levels or something?

Anyway yeah, just a reminder.

**Comment by boq** [comment]
Implemented in fd792289caecfab58dd476b30331f39b1e6dfc54
