### ISSUE TITLE
[Open Blocks Core]

### ISSUE THREAD

**Issue by Nextshot** [OpenMods/OpenBlocks#785]
Ok, so I made a modpack on the Magic Launcher... All seemed to be fine, then, An error comes -> Open blocks core : Any
I tried to download the 2 latest versions of Openblocks and OpenblocksLib for 1.7.10, But that doesnot worked... So, What is this ``Open blocks Core´´, I searched Everywhere...

**Comment by boq** [comment]
Well, probably not everywhere: this is for OpenMods Core, but basically same thing: https://openmods.info/faq.html#om-1

**Comment by Nextshot** [comment]
The jar is actually dropped on the Magic Launcher Folder

**Comment by boq** [comment]
Uh, I'm not sure how that launcher works. I can only guarantee, that it works in vanilla. Though we are not doing anything different from tons of other mods that have coremods.

Maybe post logs?

**Comment by Nextshot** [comment]
Sure, http://pastebin.com/qc0NwAvZ There it goes.

**Comment by boq** [comment]
Hmm, as I said, nor really sure how this launcher works, but FML/Forge looks for mods in `C:\Users\user\AppData\Roaming\.minecraft\mods`, while all your mods are in `C:\Users\user\Desktop\Mods Minecraft 1.7.10` - they get injected, but at later phase, so everything breaks.

So your profile is not correctly setup. Try setting `--gameDir` argument properly and keeping mods in 'mods' folder.

**Comment by Nextshot** [comment]
Now it even open to show an error.
http://pastebin.com/SeF5rBw6

**Comment by boq** [comment]
You are missing CodeChicken Core.

Closing, since it's not OpenBlocks issue.
