### ISSUE TITLE
 as I can help solve a problem openblock

### ISSUE THREAD

**Issue by HeyMenGG** [OpenMods/OpenBlocks#795]
as I can help solve a problem that does not happen openblock start the launcher and gives me an error
 Game ended with bad state ( exit code -1073741819 )
[ 17:25:00 INFO ] : Ignoring visibility rule and showing due to a game launcher crash
[ 17:25:00 INFO ] : Deleting C: \ Users \ pc \ ​​AppData \ Roaming \ .minecraft \ versions \ 1.7.10 - Forge10.13.4.1481-1.7.10 \ 1.7.10 - Forge10.13.4.1481- 1.7.10 -natives - 6614628365984 help me plss

**Comment by boq** [comment]
Sorry, but you have to look somewhere else. OpenBlocks is not even loaded in launcher.

**Comment by HeyMenGG** [comment]
thanks for quick answer is to look in other places and I redirected pole
Help me here has to be a solution plss
