### ISSUE TITLE
Builders Guide Dome only works in 3 out of the 6 possible directions.

### ISSUE THREAD

**Issue by epilimic** [OpenMods/OpenBlocks#798]
Hello. I'm trying to make a dome with the top facing South but no matter which way I rotate or wrench it, the dome refuses to show up facing South, East, or Below.

![2016-10-16_13 46 14](https://cloud.githubusercontent.com/assets/3755613/19419543/d68b9120-93a7-11e6-9b2e-66dbffdbc0a0.png)
![2016-10-16_13 46 23](https://cloud.githubusercontent.com/assets/3755613/19419544/d68d6c0c-93a7-11e6-9d9b-e452b7c2a3d9.png)
![2016-10-16_13 46 29](https://cloud.githubusercontent.com/assets/3755613/19419542/d68b6b78-93a7-11e6-8b6b-912cf13c266f.png)

Is there a trick to getting them to face in those other 3 directions or is it a bug? I've tried changing the size to inverse it but it just stops at 0 and goes flat instead of passing through and going the other way.

I'm playing on the current version 2.5.5 of SkyFactory 2.5

**Comment by boq** [comment]
Well, not exactly bug, but oversight - due to symmetry and limited possible orientations of builder block (only three instead of six) there is no way to rotate dome into this position.

I'm not sure how can this be improved, though simplest solution would be to rotate template by 90 degrees.

**Comment by epilimic** [comment]
Hrm, alright. In the meantime I suppose I can just make a massive sphere and then veinmine out half of it. I hope you're able to work out a way to get the other 3 orientations! Thanks :)
