### ISSUE TITLE
Trophy drop issues

### ISSUE THREAD

**Issue by cheatscom** [OpenMods/OpenBlocks#800]
After using this mod for some time, I have become more dissapointed with each world that I have never managed to find a trophy. After some research, I found that in the config file for OpenBlocks, I could change the drop rate for them, so I tried changing "D:trophyDropChance=0.001" to other values such as 0.05,0.5,1 etc. And no matter what I changed the value to, I was unable to get a single trophy drop, even when it should have been set to 100%. 

I tested this by spawning in around 100 mobs at a time and killing them all, and repeating for around 5-10 minutes. No luck whatsoever. I thought that there could be a mod conflict, so I removed every mod from the pack except for OpenModsLibs-0.9.1, OpenBlocks-1.5.1 and OpenEye-0.6 on version 1.7.10, and was still unable to get a drop from the same testing method, and I am using a weapon, not some kind of auto-farm. It doesn't make any difference if I use a sword, mod weapon, or potion.

I'm going to feel like an idiot if there is something I'm missing, but I've tested when its the only mod installed,made sure trophies are enabled, and used the latest version. Thank you for your time.

**Comment by boq** [comment]
Looks like you need at least one level of looting enchantment on weapon. I don't remember, if that was intended, but I will probably remove this requirement.

**Comment by cheatscom** [comment]
Thank you so much! I would have never thought that Looting would have been a requirement, but I guess it kind of makes sense. Although some weapons can't be enchanted, so some players would be unlikely to get drops unless they reverted to the vanilla weapons.

**Comment by boq** [comment]
Added bit of bias in c9e885323c438d576b6bd0a8c1e5ab3f57a71a43, so now it's possible to get trophy drop without looting sword. Also made formula more configurable.
