### ISSUE TITLE
Open Blocks I Can't Disable Graves

### ISSUE THREAD

**Issue by bunnyden** [OpenMods/OpenBlocks#801]
Hello I'm Trying To Make A Mod packed Server With Open Mod And I Can't Figure Out How To Disable Graves I Checked The Open Blocks But Thare Is Not Option That Says It Can't Desable Thank You For All You Support

**Comment by boq** [comment]
Check our FAQ: https://openmods.info/faq.html#ob-2

**Comment by bunnyden** [comment]
I Disable It From The Configs Now Thare Is Not Graves That Spawns
