### ISSUE TITLE
Grave crashes the game 

### ISSUE THREAD

**Issue by Cibernet11** [OpenMods/OpenBlocks#803]
I was playing in a custom modpack with OpenBlocks, when i died my game crashed.
I've read through the crash report and the problem seems to be caused by the gravestone being in the world or something.
[crash-2016-11-19_11.28.07-server.txt](https://github.com/OpenMods/OpenBlocks/files/601609/crash-2016-11-19_11.28.07-server.txt)

pls help

**Comment by boq** [comment]
This crash is caused by using one-year-old OpenModsLib combined with eleven-year-old Java version. Update one of those to not-ancient version.
