### ISSUE TITLE
Luggage still takes damage from Chromaticraft Pylons

### ISSUE THREAD

**Issue by Zsashas** [OpenMods/OpenBlocks#804]
It seems they can't quite kill it, but they will take it down to 0.1 health. Either that, or mine got really lucky.

![2016-11-23_10 37 15](https://cloud.githubusercontent.com/assets/6917535/20574386/08b0e450-b169-11e6-882d-0b08b54feace.png)

**Comment by boq** [comment]
As long as it lives, I consider it minor bug (it cannot be seen without health bar mods).

Probably caused by some Chromaticraft hackery (directly manipulating health?), since luggage ignores all damage.

**Comment by Zsashas** [comment]
@ReikaKalseki ? How do pylons do damage?

**Comment by boq** [comment]
If it's https://github.com/ReikaKalseki/ChromatiCraft/blob/master/TileEntity/Auxiliary/TileEntityPylonTurboCharger.java#L359 then it's not problem (still done with `attackEntityFrom`). Same with poison effect. So maybe it's something else.

Anyway, if there is something that may ignore `Entity.isEntityInvulnerable` please let me know.

**Comment by ReikaKalseki** [comment]
What is its entity name or class? I can make pylons ignore them. Nothing can prevent pylon damage once it decides to attack.

**Comment by boq** [comment]
I'm not really fan of special casing and creating hidden dependencies like that. Can you restrict damage to entities that return `Entity.isEntityInvulnerable() == false`? There are really only few entities that set it (in Forge it's only FakePlayer and I don't see why that would require damage).

Anyway, if damage is done with https://github.com/ReikaKalseki/ChromatiCraft/blob/c9fbdb44248ade76cd683a31aeff3b0bbcd3fdf3/Auxiliary/ChromaAux.java#L235 then I really don't see that as big problem - it won't kill luggage and health can be restored by picking and placing luggage back.

**Comment by ReikaKalseki** [comment]
> Can you restrict damage to entities that return Entity.isEntityInvulnerable() == false

No. I do not trust things like Draconic Armor.

**Comment by boq** [comment]
Welp, here comes nuclear option: 940569f998bc4e6b32423a02753f4fcf16519736
