### ISSUE TITLE
Adventure Backpacks not being put in graves

### ISSUE THREAD

**Issue by Flexico** [OpenMods/OpenBlocks#806]
By default, if you die while wearing an <a href="http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2252109-wip-adventure-backpack-mod-beta-0-8c-updated">Adventure Backpack</a>, it gets placed in the world as a block. The config file does give an option to have it drop as an item, which I want so that it gets put in the OB gravestone. However, with that option enabled it still gets dropped as an item next to the grave.

**Comment by Eufranio** [comment]
The devs of Adventure Backpack have already noticed the issue: **https://github.com/runescapejon/AdventureBackpack2/issues/27**

**Comment by Flexico** [comment]
Ah good, thanks for the info~
