### ISSUE TITLE
When a player dies the server dies with it

### ISSUE THREAD

**Issue by linetreax** [OpenMods/OpenBlocks#814]
so whenever a player is killed by and thing the server crashes thank you for who ever looks at this.

code:
[ERROR REPORT.txt](https://github.com/OpenMods/OpenBlocks/files/781528/ERROR.REPORT.txt)

-------------------------------------------------------------------------------------------------------------------
P.S the server says it's still on when this happens

**Comment by boq** [comment]
`net.minecraft.server.v1_10_R1`...

We don't even have OpenBlocks for that version.
