### ISSUE TITLE
New ladder

### ISSUE THREAD

**Issue by forestbat** [OpenMods/OpenBlocks#815]
The ladder in minecraft must be placed on the wall，so hope you can make a triangular ladder which can be placed on the ground and change its height。
Thank you very much。

**Comment by redstonedude0** [comment]
Perhaps rather than adding a new block, and making it triangular (which would be more awkward), the existing scaffolding block could be modified to allowing climbing on every side as if it was covered in ladders (as the IC2 scaffold currently does).
