### ISSUE TITLE
OpenMods missing on latest

### ISSUE THREAD

**Issue by Eufranio** [OpenMods/OpenBlocks#819]
I just updated my pack, and it say it's missing OpenMods, but I have it. Versions:

OpenBlocks-1.7.10-1.6
OpenModsLib-1.7.10-0.10-snapshot-465
Message:

![1](http://image.prntscr.com/image/8ca6c3392c8b43d9804ef6341b5fc215.png)

**Comment by boq** [comment]
Some other mods want't OpenMods 0.9.*. Probably OpenPeripheral.

**Comment by Eufranio** [comment]
Oh, true. Thanks!
