### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by fcpwiz** [OpenMods/OpenBlocks#823]
OpenBlocks Version: OpenBlocks-1.10.2-1.6.jar

I'm running SpongeForge 1.10.2 and it crashes. Here's the log: https://gist.github.com/fcpwiz/2709ebcf264d223540f8e89f1bd39bbd

**Comment by boq** [comment]
First of all, fixed yesterday.

Anyway, the fact that you are trying to run it on non-standard (standard == pure Forge) suggests that you are preparing public server. I strongly suggest against it, since in alpha I'm reserving rights to make breaking (as in "world breaking") changes.
