### ISSUE TITLE
Crash when eating mushroom stew or..

### ISSUE THREAD

**Issue by DeadSix27** [OpenMods/OpenBlocks#824]
right clicking a bowl in general? 

Either way, not sure if you want issue posts for 1.10.2 yet but here is the stacktrace anyway:
https://gist.github.com/DeadSix27/f198ddf0584fb2df0defbb397a58030a
Say if you need the full log and or no issue posts for 1.10.x anymore..

**Comment by boq** [comment]
https://github.com/OpenMods/OpenModsLib/issues/64 duplicate.

For now I'm keeping it unfixed, as a safeguard against wider use of this pre-alpha version.

**Comment by DeadSix27** [comment]
@boq I recommend adding a issue template (https://github.com/blog/2111-issue-and-pull-request-templates)
So that in the future people will see a text like, "No issue reports for 1.10.x yet!" :)

**Comment by boq** [comment]
Fixed in OpenModsLib
