### ISSUE TITLE
Crash between two players

### ISSUE THREAD

**Issue by forestbat** [OpenMods/OpenBlocks#827]
My girlfriend and me both used OMlib snapshot 22 and OB snapshot 20，but my game is normal and hers crashed。 
It's my log：http://paste.ubuntu.com/24917683/
This is her log：http://paste.ubuntu.com/24917691/
What happened？
Before this we tried the latest snapshot of OB and OML，but they performs worse than 20.

**Comment by boq** [comment]
Fixed that. But please note that trying to play before alpha/beta release is not recommended - I still reserve rights to make world breaking changes between snapshots.
