### ISSUE TITLE
[1.10.2] /dev/null seems to add NBT data to items without it?

### ISSUE THREAD

**Issue by apemanzilla** [OpenMods/OpenBlocks#829]
This is kind of a strange issue I encountered, when placing items that **do not** have NBT data into the slot in the /dev/null, it seems to assign empty NBT data to the stack. This can be seen with advanced tooltips enabled, the stack will now show `NBT: 0 tag(s)`.

Steps to reproduce:
1. Spawn in a /dev/null and a stack of stone.
2. Verify that stone doesn't have NBT data
3. Open GUI for /dev/null and put stone into slot
4. Note that stone now has empty NBT data

This doesn't seem to affect items that already have NBT data - such as banners or tipped arrows - but it does make it effectively useless for removing excess items like stone, which no longer stack with the NBT-ified stone in the /dev/null and don't get collected by it.

Edit: Interestingly, if you add one item from a stack to the /dev/null (Take a clean stack of stone, right click to drop one into the /dev/null slot) the entire stack is modified.

**Comment by boq** [comment]
Should be fixed.
