### ISSUE TITLE
[1.10.2] Crash with buckets and other mod fluids

### ISSUE THREAD

**Issue by BoxOfFlex** [OpenMods/OpenBlocks#833]
Versions:
- OpenMods: 0.1 snapshot 52
- OpenBlocks: 1.6 snapshot 54

Short Error:
```
java.lang.NullPointerException: Unexpected error
	at openmods.liquids.BucketFillHandler.onBucketFill(BucketFillHandler.java:62)
```

Full Log: https://hastebin.com/ifimazoyol

Dunno if it helps to recreate, but specific mod fluid was regeneration water (or whatever its called) from Botania.

**Comment by boq** [comment]
#824 duplicate.
