### ISSUE TITLE
[1.10.2] Crash on startup - "B:grave=false"

### ISSUE THREAD

**Issue by MysticFlowP** [OpenMods/OpenBlocks#837]
...\config\openblocks.cfg
> B:grave=false

https://pastebin.com/raw/arg7GHH4

#### Using
- OpenBlocks-1.10.2-1.7
- OpenModsLib-1.10.2-0.11

**Comment by Spazmunki13** [comment]
I'm getting the crash as well.

https://pastebin.com/ZPVceAah

**Comment by boq** [comment]
Accidentally fixed via f7fcacd9be205d75bc8f52915d5741bf4e16ecbe.  Though problem still existed for few other blocks.
