### ISSUE TITLE
trying to use openblocks for 1.10.2 causes instant soft-crash.

### ISSUE THREAD

**Issue by border999** [OpenMods/OpenBlocks#838]
The instant I attempt to even start minecraft with openblocks and openmodslib installed it crashes. No crash log generates.
All that is in the log is at the link below.
https://pastebin.com/DKyDzXdq

**Comment by boq** [comment]
`java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin`

Well, what do you expect when you start 1.7.10 coremod on 1.10.2?

**Comment by border999** [comment]
hasn't there been exactly one version of openblocks made for 1.10.2?
The version I was using was 1.7

**Comment by boq** [comment]
Uh, what? Again: for unknown reasons you are using 1.7.10 mod on MC 1.10.2. This is not OpenBlocks issue.

**Comment by border999** [comment]
*Sigh* Nevermind
