### ISSUE TITLE
OpenBlocks and Optifine incompatible, crashes on load

### ISSUE THREAD

**Issue by FlaggedBrad** [OpenMods/OpenBlocks#839]
[Crash Report](https://pastebin.com/raw/SkJs4BTM)

OptiFine_1.10.2_HD_U_E3 and OpenBlocks-1.10.2-1.7 are incompatible and cause the game to crash during the loading process. Running on forge version 12.18.3.2316 and minecraft 1.10.2

**Comment by boq** [comment]
Ah, yes, another part of great chain of duplicates: #835, #831. Here's Optifine issue for reference: https://github.com/sp614x/optifine/issues/787
