### ISSUE TITLE
I'm sorry, I know devs hate this kind of question, forgive me, please, but, when there will be a 1.12 version?

### ISSUE THREAD

**Issue by Lion4K** [OpenMods/OpenBlocks#844]
Question.

**Comment by boq** [comment]
After 1.10/1.11 release, naturally.

**Comment by Lion4K** [comment]
![image](https://user-images.githubusercontent.com/10391955/29398582-c527ebc4-82fb-11e7-9313-c6b245e1f5d3.png)
Seems pretty close then :D
Is there any pre-release I could help test or something?

**Comment by boq** [comment]
1.12 snapshots are now available.
