### ISSUE TITLE
Can't place sprinkler on other blocks

### ISSUE THREAD

**Issue by Zyles** [OpenMods/OpenBlocks#845]
I want the ability to place the sprinkler on other blocks than the openblocks tank.

Such as:

- Forestry Raintank
- EnderIO Fluid Tanks and Reservoir

I can't seem to do it, but I think it was possible before.

Thank you.

**Comment by Zyles** [comment]
Nevermind this. I had a keybind conflict which didn't allow me to place it. Seems to work as usual.

**Comment by boq** [comment]
Nothing has changed: if you can place vanilla's lever on block, you should be able to place sprinkler in there.
