### ISSUE TITLE
[MC 1.7.10, OB 1.6] Elevator Height Change

### ISSUE THREAD

**Issue by Ruok2bu** [OpenMods/OpenBlocks#850]
Elevator blocks will not work when the next floor is 13 blocks away.  I tried _maxPassThrough=150_ and it didn't change anything.  Then i tried _ignoreAllBlocks=true_ and it also didn't change anything.

Is there a hard coded limit of 12 blocks?

**Comment by boq** [comment]
`maxPassThrough` is for maximum number of solid block between two elevators. What you really want is `searchDistance`.
