### ISSUE TITLE
Testing the OpenBlocks 1.12.2 and collect some issues

### ISSUE THREAD

**Issue by JoeSGT** [OpenMods/OpenBlocks#854]
Open Blocks issues

1. Other mods Creative tab is showing OpenBlocks Items in them even vanilla creative tabs
2. if you look around Tree get glitch and they Flicker GIF: https://gyazo.com/e14810c3a3fd1191243aeb613a541a86
3. Block Placer can use to Grief with the Sponge plugin called GriefPrevention, possibly best to use fakeplayer or something to prevent it
4. Paint Brush right click in Grass or any blocks and it turn too Canvas blocks
5. creative Distory blocks  is having a texture error with OpenBlocks here what i am talkin about https://gyazo.com/e74305cd3ba849da81663fb2cd1a0410
6. If you Mess with Magic Crayon on serverside it spam with this error and sometimes kick you for internal server error https://pastebin.com/T7e8DGuD with this i was using Black Crayon Glasses and Black Crayon
7. and i got this crash report https://pastebin.com/Z7gPyPZc from messing with  Black Crayon Glasses and Black Crayon not sure how i did it
Version i used 
OpenBlocks-1.12.2-1.7.2-1.12.X-snapshot-4
OpenModsLib-1.12.2-0.11.2-1.12.X-snapshot-6
forge-1.12.2-14.23.1.2559
if those get's fix i think it's stable

**Comment by boq** [comment]
1. Fixed
2. Can't reproduce. I don't see any modded block in screenshot, so it's either vanilla issue or some generic "fixer" mod. I usually don't accept rendering glitches when Optifine is present.
3. It already uses (and has always used) fake player. Please see [FAQ](https://openmods.info/faq.html#om-0) for list. Also, it already respects Forge events, so it should work. Please be more specific.
4. Working as expected - paintbrush is supposed to paint any "normal" block.
5. Looks like rendering glitch. See 2.
6. Fixed
7. Not sure how it happened (I blame Optifine), but fixed.

**Comment by JoeSGT** [comment]
ah okay i took out Optifine and i am still getting that weird tree effect
but other issues that was related to optifine is fixed, i look a little more of this issue with the Tree's
and it seem to be the foamfix-0.8.0-1.12-law was causing the issue with OpenBlocks
i took it out and the Tree's went back to normal

3. I had a server setup with GriefPrevention - Spongepowered and i can bypass someone claim by using Block-Placer on the border of there claim and i did not have any permission to there claim either to break or block, or interact with anything and i can use the block placer to place the block on the border of there claim. now i am tested with the new update you just push out i am unable to right click the block placer to access the gui this is version OpenBlocks-1.12.2-1.7.2-1.12.X-snapshot-5 and OpenModsLib-1.12.2-0.11.2-1.12.X-snapshot-7

but most of the issue are fixed thanks you

**Comment by JoeSGT** [comment]
GIF: https://gyazo.com/c1c368eca1f89d4dea7d64fd3c539cc6
in chat is said `You don't have permission to use minecraft:redstone_block on a minecraft:dirt`
as you can see i can use Block Placer to place blocks on the border of someone claim
https://gyazo.com/52950973caeec4744e83d10cc2e26092

**Comment by JoeSGT** [comment]
And Also it seem that Block Breakers are not breaking any blocks when i power it with redstone

**Comment by JoeSGT** [comment]
Going to close this, it seem most of the issues are fixed
