### ISSUE TITLE
Issue 1.12.2 Crash 

### ISSUE THREAD

**Issue by DumbSlayer** [OpenMods/OpenBlocks#855]
OpenBlocks OpenBlocks-1.12.2-1.7.2-1.12.X-snapshot-8 every time i add optifine it makes me crash

[crash-2017-12-06_18.38.38-client.txt](https://github.com/OpenMods/OpenBlocks/files/1549514/crash-2017-12-06_18.38.38-client.txt)

and there is my crash report

**Comment by boq** [comment]
Uh, you have snapshot 4, this issue should be already fixed.
```
	| UCHIJA | openblocks               | 1.7.2                    | OpenBlocks-1.12.2-1.7.2-1.12.X-snapshot-4.jar   | None                                     |
```
