### ISSUE TITLE
OpenBlocks refuses to compile on Java 9

### ISSUE THREAD

**Issue by roboderpy** [OpenMods/OpenBlocks#856]
```
$ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by roboderpy** [comment]
Seems like even Minecraft can't launch on Java 9 😂

But still, be ready for Java 9.

**Comment by boq** [comment]
Minecraft, FML, ForgeGradle (real culprit in this issue) and probably other stuff require rather big fixes (or even rework) before I have to start worrying about my code.
