### ISSUE TITLE
[1.12.2] When rightclick on hang glider it becomes invisible in inventory

### ISSUE THREAD

**Issue by Morpheus1101** [OpenMods/OpenBlocks#863]
When rightclick on hang glider it becomes invisible in inventory untill such time as you re-click in the spot the glider was originally when it then returns to your inv.

**Comment by boq** [comment]
Ehh, it's  more or less intended behavior, since I want it to not be rendered in hand when deployed, but I guess I may try to add special case for inventory.

**Comment by Morpheus1101** [comment]
The only issue i see is that if you want to take it off after using it, its not displayed in any armor//bauble slot or in the inventory

**Comment by boq** [comment]
It's still in hand/offhand and visible in third-person. But I understand this may cause confusion.
