### ISSUE TITLE
Launcher crash 1.12.2 

### ISSUE THREAD

**Issue by Leosky** [OpenMods/OpenBlocks#864]
The game crash few second after having clicked ont the launch game button.

https://gist.github.com/Leosky/f1bf7060bec12ae77350a0b2246c4659

**Comment by boq** [comment]
`OpenModsLib-1.11.2-0.11.3.jar`...

Please use correct version of OpenModsLib, this file is for MC 1.11.2.

**Comment by Leosky** [comment]
ok i check that everytime i have a crash but not this time -_- sorry for that
