### ISSUE TITLE
1.12 Redstoneblock dupe / "Crash"

### ISSUE THREAD

**Issue by tigerdan2** [OpenMods/OpenBlocks#865]
OpenBlocks-1.12.2-1.7.3
Tested in SP

Dupe+"softlock/crash"

when you place a redstoneblock infront of the blockbreaker it puts one in a chest behind the blockbreaker but also drops one
https://streamable.com/krjgj

also by putting blockbreaker/blockplacers in a circle you can crash the game like this
https://streamable.com/e7xi0

Funfact 
the "circle duper" could theoretical dupe 2.2K redstoneblocks per tick -> 45k redstoneblocks per second
of course game cant handle that
Edit it looks like the circle even duplicates "infinit" redstoneblocks / tick

**Comment by boq** [comment]
"Crash" - I will limit rate of operations per tick for both placer and breaker.
Duplication - can't reproduce with OpenBlocks only. Can you test it without pipes (i.e. by loading placer manually)?

**Comment by tigerdan2** [comment]
Yeah i can also confirm that it was not openblocks that caused the glitch
I tried it in another pack wich is running the same version (even same jar)
and it does not dupe.
So basicly this issues can be closed.
