### ISSUE TITLE
Bad performance with Sponge (from OpenBlocks)

### ISSUE THREAD

**Issue by JoeSGT** [OpenMods/OpenBlocks#867]
Hello when your in the ocean or any type of massive water and place just about 3 of them you will lag the server or singleplayer to about 13 tps sometimes or less tps, depending how much you place them 
this does not happen with vanilla sponge
Version i am using is
forge-1.12.2-14.23.1.2581
OpenBlocks-1.12.2-1.7.3
OpenModsLib-1.12.2-0.11.3

**Comment by boq** [comment]
Eh, this behaviour was expected, since sponge worked continuously, but also updated neighbours. We had discussion about restoring old functionality (non-update) in #614, but I have no idea why it was changed in first place, so as an experiment I'm restoring old behaviour - should reduce lag.
