### ISSUE TITLE
[1.12.2] Fence's connection still appears

### ISSUE THREAD

**Issue by JonasCiss** [OpenMods/OpenBlocks#871]
Still appears. The fence is made of wood from BOP. I use the latest version of OP. This issue was closed a few days ago. 
![2018-01-03_10 33 48](https://user-images.githubusercontent.com/26455012/34515447-653823d4-f072-11e7-9473-c8e7635eb9a2.png)

**Comment by boq** [comment]
"Latest version of OB" is bit vague. This issue is fixed in development version (snapshot), but it has not been released yet (so in 1.7.4 it not fixed yet).
