### ISSUE TITLE
Fan

### ISSUE THREAD

**Issue by TheSnowyChickens** [OpenMods/OpenBlocks#873]
Hello,

the Fan is a bit weird (I don't know, how to create gif's :D )->
![2018-01-06_21 49 25](https://user-images.githubusercontent.com/29357962/34643825-7f17ede6-f32b-11e7-94c7-6f14fde57490.png)
During it rotates it change from white to black (short : Its flickering)

MC 1.12.2
OpenBlocks ->1.7.4
OpenLib ->0.11.4
Forge ->2584

**Comment by boq** [comment]
Sorry, I don't investigate rendering glitches when Optifine is present. Especially when this issue is not reproducible without it.

**Comment by TheSnowyChickens** [comment]
Ohhh, sry. In 1.7 it worked with Opti"fine" ( :D ) thats why I thought it works.
