### ISSUE TITLE
[1.12.2] Screen is flickering in OpenBlocks-1.12.2-1.7.4.jar

### ISSUE THREAD

**Issue by dragon3025** [OpenMods/OpenBlocks#878]
I removed the mod and the flickering stopped, so I think this mod is causing it.

EDIT: It seems to happen when I open the inventory. After closing the inventory it still flickers.

**Comment by dragon3025** [comment]
Nevermind, I added it back it and it back in and it stopped. I don't understand what happened because I didn't change any settings.

**Comment by boq** [comment]
Eh, I've been trying to fix that one for months. Problem is that it seems mostly random, so I can't even confirm if that's something in OpenBlocks.

**Comment by OnyxNewt** [comment]
I've noticed the problem with flickering too. The information might already be known to you but it's related to mipmapping. If you turn off mipmaps it removes the "flicker". 

So I went a little further and discovered that the problem only occurs when the snow golem trophy appears on screen.

Hopefully that helps.

**Comment by boq** [comment]
Thank you, it was indeed helpful and I was able to fix that issue.
