### ISSUE TITLE
Auto Enchantment Table does not accept liquid XP

### ISSUE THREAD

**Issue by pinter-gabor-at** [OpenMods/OpenBlocks#879]
OpenBlocks-1.12.2-1.7.4.
OpenModsLib-1.12.2-0.11.4.
There is no way to input liquid XP into Auto Enchanment Table.
Auto drink does not draw liquid from any OpenBlock Tank or Thermal Expansion Portable tank, placed on any side of the Auto Enchanment Table.
Pumping liquid XP into Auto Enchantment Table with Thermal Dynamics Fluiducts does not work, the pipe does not even connect to the Auto Enchantment Table.
Placing XP Drain on top of the Auto Enchantment Table does not work either.

Interestingly OpenBlocks Tanks, Thermal Expansion Portable Tanks and Thermal Dynamics Fluiducts work with each other flawlessly in every other combination, so the bug must be in Auto Enchantment Table.

**Comment by vanessaenos** [comment]
I’m having the same issue and I’ve tried everything. Nothing works. I’ve watched tutorial after tutorial, so I know I’m not missing any steps, it just doesn’t work.
