### ISSUE TITLE
[1.12.2] Empty Maps 1:4 and 1:8 do not have recipes in JEI

### ISSUE THREAD

**Issue by Boomflex** [OpenMods/OpenBlocks#881]
Openblocks version: 1.7.4

Empty Maps 1:4 and 1:8 do not have recipes in JEI.

**Comment by boq** [comment]
This recipe is dynamic, but I've decided to add "fake" one to at least hint the possibility of vanilla-like scaling mechanism.

Unfortunately, there can be only one "fake recipe" per actual recipe object, so 1:1 to 1:2 is the only one that JEI sees (adding multiple recipes for different scales would just lag crafting). Also, in released version fake pattern is invalid (shifted one field to left), though actual recipe should work.
