### ISSUE TITLE
Elevator doesn't work

### ISSUE THREAD

**Issue by yafta98** [OpenMods/OpenBlocks#882]
Elevators won't work in 1.12.2. Tried in survival and creative, I have more than enough XP. Using version 1.7.4 for openblocks and openmodslib, doesn't work with 1.7.3 either.

[Gif of proof](https://gyazo.com/fc16007b706e776a161b10e69ef7eb6d)

**Comment by boq** [comment]
Well, as usual, worksforme (wouldn't release, if that was broken), so let's troubleshoot what's wrong with your install. I need OpenModsLib and Forge versions. Also, modpack name and version, if this is modpack.

**Comment by yafta98** [comment]
OpenModsLib is 0.11.4, Forge is 14.23.1.2583, downgraded to recommended version 2555 and still doesn't work. It's a custom [modpack](https://www.technicpack.net/modpack/yafta98s-modpack.1109917) that I use mainly for singleplayer.

**Comment by boq** [comment]
Better Sprinting [replaces](https://github.com/chylex/Better-Sprinting/blob/master/src/main/java/chylex/bettersprinting/system/core/TransformerEntityPlayerSP.java#L100) call to Forge hook `ForgeHooksClient.onInputUpdate`. Nothing can be done on my side.
