### ISSUE TITLE
No OpenGL context found in the current thread.

### ISSUE THREAD

**Issue by trilexcom** [OpenMods/OpenBlocks#884]
hi OpenBlocks

I am getting a error msg from latest version of OpenBlock and OpenModsLib

The game crashed whilst initializing game
Error: java.lang.RuntimeException: No OpenGL context found in the current thread.

OpenBlock version: -1.75
OpenModsLib Version :  0.11.5
Forge version: 2607
MC : 1.12.2
Link to crash report or log: https://pastebin.com/3VPu77PE
Singleplayer or multiplayer: both
Additional information: when you downgrade to last release version its working fine. 

Thanks 

Mat.

**Comment by trilexcom** [comment]
looks like its not open blocks its foamfix if you update foamfix to version 0.9.2 openblock is ok i am going to close this ticket thanks again mat

**Comment by trilexcom** [comment]
looks its open blocks when i downgrade its working fine and we are using foamfix 0.9.2

**Comment by boq** [comment]
Blame is still on FoamFix (since it trades compatibility for some speed) with some help from Forge. Still, I can do some workarounds on my side.

**Comment by trilexcom** [comment]
ok should i report it to foamfix than ? and close this ticket?

**Comment by boq** [comment]
You can, to let them now it's possible issue. I also opened https://github.com/MinecraftForge/MinecraftForge/pull/4721 to fix it property. As for OpenBlocks, I will be pushing workaround soon.

**Comment by trilexcom** [comment]
thank you so much i will let them know about this issue

**Comment by asiekierka** [comment]
Yep, this is totally my fault! (In my defense, however, it *is* an experimental feature and I think it also is disabled by default in more recent versions.)

**Comment by asiekierka** [comment]
@boq If the fix ends up sticking around in Forge's PR hell for more than necessary, would you mind if I add it to FoamFix directly?

**Comment by trilexcom** [comment]
thanks asie and welcome back :)

**Comment by boq** [comment]
Sure. Quick google shows that it's not first instance of that problem (see here: https://github.com/amadornes/SCM-Localization-Issues/issues/110).

**Comment by trilexcom** [comment]
boq just a simple question for you i didn't wanna create a new issue sense its not a open block issue ? when we have primalcore in our pack the sleeping bag won't work if you click it ? you gotta put it in my chest plate area? is that a openblock issue or primal issue? because when i remove primal its working fine ? and how do i get a log for that? mat

**Comment by trilexcom** [comment]
ah thank you you are very awesome again i really appreciate it
