### ISSUE TITLE
Elevator block doesn't work in a cubic chunks world.

### ISSUE THREAD

**Issue by border999** [OpenMods/OpenBlocks#886]
https://github.com/OpenCubicChunks/CubicChunks/wiki
I'm thinking that the elevators can't actually figure out where it is in relation to other elevators due to how cubic chunks alters the way the world is run.

**Comment by boq** [comment]
I'm unable to found any issue - elevators work both >256 and <0.

Please describe your test procedure.

**Comment by border999** [comment]
hmm, perhaps I'm on an old version of openblocks. Let me look into it.
