### ISSUE TITLE
OpenBlocks Crash when loading the Stencil Item

### ISSUE THREAD

**Issue by Vehicola** [OpenMods/OpenBlocks#888]
I currently am trying to install OpenBlocks, but when forge loads the Stencil item, it crashes.

Here's an Error Log if I filter for "Stencil":
https://gist.github.com/Vehicola/befb4996684362441b58e0a20a7e0df5

And Here's and Error Log if I filter just for "OpenBlocks":
https://gist.github.com/Vehicola/906e0030c69939daf7c1095c80e6ea4d

If you need more, please tell me and I'll be happy to help. Thanks!

**Comment by boq** [comment]
Ok, so couple of general notes first about error reporting:
- Always include Minecraft and mod version next time. In this case I'm able to guess it's 1.10, but it's not always that easy.
- Post full logs. I can't diagnose just with those lines.

Anyway, it seems like compatibility issue, There should be log starting with lines `Exception caught during firing event` that points to actual culprit.
