### ISSUE TITLE
asked for non-existent maps

### ISSUE THREAD

**Issue by DanOsteel** [OpenMods/OpenBlocks#889]
So this issue keeps coming across in our server log, and we believe it to be a cause of lag on the server. Can anyone help me?

 [01:03:10 INFO]: openblocks.common.MapDataManager.onMapDataRequest(MapDataManager.java:145): Player EntityPlayerMP['HexxTech'/1284653, l='world', x=3616.44, y=63.00, z=-7597.29](HexxTech at 3616.43684463638,63.0,-7597.293248872368) asked for non-existent maps {0}

It pops up and spams the log several times. "Obviously player name changes"
I've attached a short log below.

[latest.log](https://github.com/OpenMods/OpenBlocks/files/1743050/latest.log)

**Comment by DanOsteel** [comment]
Server Specs

Intel  i7-6700K
4c/8t - 4GHz /4.2GHz
32GB DDR4 2133 MHz
SoftRaid  2x480GB  SSD
250 Mbps  bandwidth
vRack: not included

**Comment by DanOsteel** [comment]
Mod list: AcademyCraft
AE2 Stuff
Agricraft
ArsMagica
Ambience
Animation API
Applied Energistics 2
Arcane Engineering
Architecture Craft
Armourers Workshop
Aroma Core
AW Core
bdlib
Big Reactors by E. Beef
Blood Arsenal
Blood Magic
Botania by Vazkii
Botanical Addons
Carpenters Blocks
Chisel
CodeChickenCore
CoFH Core
CoFH Lib
Custom Main Menu
Damage Indicators
DecoCraft
Ender Core
EnderIO
EnderStorage
Ender Tech
Ender Utilities
Extra Cells
Extra TIC
Extra Utilities
Fast Craft
Forbidden Magic
Forestry
GuideAPI
iChun Util
Immersive Engineering
Immersive Integration
Inventory Tweaks
Iron Chest
Journey Map
Lamda Lib
LegacyJavaFixer
Magical Crops
Malisis Core
Malisis Doors
Mantle
mcjtylib
Mekanism
Mekanism Generators
Mekanism Tools
Metallurgy
Metallurgy Core
Minefactory Reloaded
Minetweaker 3
Minetweaker
DoubleDoorDevelopment
NEI Addons
Nodal Mechanics
No More Recipe Conflicts
NotEnoughItems
NotEnoughThaumcraftTabs
Open Blocks
Open Mods Lib
Optifine
Pam's Harvestcraft
Resource Loader
SimplyJetpacks
tcinventoryscan
Tinkers Construct
Thaumcraft
ThaumicEnergistics
ThaumicHorizons
Thaumic Tinkerer
Thaumic Upholstery
Thermal Dynamics
Thermal Expansion
Thermal Foundation
TinkerIO
Waila
Waila Harvestability
Witchery

**Comment by boq** [comment]
This is does not cause lag, it's just debug information from height map - displayed when player looks at one without any data (usually triggered by NEI and such) for the first time. If that bothers you, just create single height map (pop empty one into cartographer). Or make sure config option `reportInvalidRequest` is set to false.

For lag problems I suggests looking at [Sampler](https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-25-note-all-posts-of-new-members-need-to-be-approved-firs/). Trying to find lag based on logs leads nowhere.

PS. All that information and Minecraft version is still missing (I can guess it's 1.7.10, but it's always nice to have it explicitly) .

**Comment by DanOsteel** [comment]
Thank you for you help, and yes it is 1.7.10. Appreciate it boq.

**Comment by Pato0101** [comment]
i keep getting this message on the server console right before it freezes completely(no commands work, cant close server with stop command)
