### ISSUE TITLE
[1.12.2] Can't extract fluids from tank with a bucket

### ISSUE THREAD

**Issue by 2ndkirbyever** [OpenMods/OpenBlocks#890]
I was planning on using OpenBlocks tanks to store liquid starlight from Astral Sorcery, but when I tried to take the starlight out with a bucket, I noticed that it was stuck in there. I was able to move the fluid to a different tank using Extra Utilities transfer nodes, but after I noticed this, I tried it with water. Same thing: buckets don't seem to extract from tanks.

OpenBlocks-1.12.2-1.7.6
OpenModsLib-1.12.2-0.11.5

**Comment by boq** [comment]
Can't reproduce. Are you shifting when you try to extract?

**Comment by 2ndkirbyever** [comment]
I was not. In the past, the tanks allowed you to extract fluid from simply right-clicking, and I thought that behavior carried over to 1.12.
