### ISSUE TITLE
Game halts when a Block Placer places Gravel

### ISSUE THREAD

**Issue by TowardtheStars** [OpenMods/OpenBlocks#895]
When trying to make a Block Placer place more than 1 gravel from a high place and to provide it a continuous redstone signal, the game will halt immediately without giving a crash report or something alike. And sometimes may summon a fallingsand entity that cannot turn to block or drop as an item.
An example to reproduce: 
1. Place a Block Placer facing horizontally, provided that gravel can fall after being placed.
2. Put in 64 gravel or sand at a time.
3. Give it a continuous redstone signal.

**Comment by boq** [comment]
Can't reproduce. Though it sounds like issue reported some time ago (#851).

Please always provide version when reporting bugs.
