### ISSUE TITLE
[1.12] Cannot extract liquid from tank with an empty bucket

### ISSUE THREAD

**Issue by quixQuery** [OpenMods/OpenBlocks#898]
forge-14.23.2.2629
JEI-4.8.5.159
The One Probe - 1.4.19
Default Java version shipped with Minecraft

Also:
OpenBlocks- 1.7.6
OpenModsLib- 0.11.5

There are literally no other mods in the instance.

I try to extract lava from a tank with lava in it by right-clicking on the tank with an empty bucket. It does not extract the fluid. I am able to replicate this in a fresh instance with no setting/config changes. I can add fluid to the tank, but cannot take it back out. The same can be said for water.

**Comment by boq** [comment]
#890 duplicate?
