### ISSUE TITLE
1.7.10 OpenBlocks crash

### ISSUE THREAD

**Issue by pchard** [OpenMods/OpenBlocks#899]
Added OpenBlocks to server today.

Got this error:
https://pastebin.com/f83PaCD9

**Comment by boq** [comment]
Ok, so basic idea is that I wouldn't release something that crashed on startup. And if I did, it would certainly take less than year to get report on that. So it's pretty much not OpenBlocks issue. Also, this version of MC is no longer supported and non-Forge was never supported in first place.

Problem seems to be related to malformed class file, somehow referenced by 
`openblocks/common/TrophyHandler`.
