### ISSUE TITLE
[1.12.2] Intended tank behaviour?

### ISSUE THREAD

**Issue by 016Nojr** [OpenMods/OpenBlocks#902]
Is it intended to require players to sneak-right click empty buckets to fill them up from the tanks?
Would be better if it was just a normal right click without having to hold down the sneak key

**Comment by boq** [comment]
It was compatibility fix for something (probably ghost blocks). After 1.10.2 port it started having different side effects, but now seems not needed, so  I removed it via e6be1e57ec3be6c362ccd5049cd0ba273a1d0189.
