### ISSUE TITLE
Skyblocks and OptiFine shaders

### ISSUE THREAD

**Issue by sp614x** [OpenMods/OpenBlocks#908]
Currently the skyblock renderer is disabled when OptiFine is installed. This can be overriden by setting `optifineOverride=true` in the config. The reason for this seems to be that skyblocks are not compatible with shaders.

It would be better to dynamically enable/disable skyblocks rendering depending on whether shaders are enabled. The easiest way to do it is to call "Config.isShaders()" via reflection.

This would fix the skyblocks for the majority of users that don't have shaders enabled.

**Comment by boq** [comment]
It's default package, right?

Also, when this value can change? Only during resource reload after shader initialization?

**Comment by sp614x** [comment]
This is default package. Enabling/disabling shaders triggers resources reload.
The method itself is very fast (checks cached boolean value).
