### ISSUE TITLE
imaginary block nbt data

### ISSUE THREAD

**Issue by Shane371** [OpenMods/OpenBlocks#911]
Trying to figure out the format for imaginary blocks or if there is one. Dont mean the crayons the transparent crayon block version. All i have so far by looking at some of the code and various console commands is this.
 <openblocks:imaginary>.withTag({Color: 1973019, IsInverted: false, Shape : "Block" })

Not sure if that is even close though. Just looking for an example to go by.

**Comment by boq** [comment]
Relevant code: https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/tileentity/TileEntityImaginary.java#L97:
- int `Color` (optional, if not present, it's pencil)
- bool `IsInverted` - non-inverted block block is solid only when visible, this inverts that
- byte `Shape` - 0 (full block), 1 - panel at y=1, 2 - panel at y=0.5, 3 - stairs (https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/block/BlockImaginary.java#L46)

**Comment by Shane371** [comment]
Thanks for the reply, I was not even close to figuring out  shape.
