### ISSUE TITLE
Skyblocks not working with shaders

### ISSUE THREAD

**Issue by Hauteknits** [OpenMods/OpenBlocks#912]
I know this is a known issue, but I have yet to find a fix (if there is one). I am using optifine shaders with SEUS 11.0. Here are some screenshots along with a crash report. I can provide more info and screenshots if needed. Ver: 1.7.10. OpenBlocks: 1.6, Openlib: 0.1, Optifine Ultra: E7. NVIDIA GTX 970, Intel i7-4790k 4.3 GHz
![2018-05-28_20 17 38](https://user-images.githubusercontent.com/22118377/40636534-46e49a84-62b4-11e8-8c71-91aa099a5c1a.png)
![2018-05-28_20 17 08](https://user-images.githubusercontent.com/22118377/40636535-47011362-62b4-11e8-9f63-8ef3970b7237.png)
![2018-05-28_20 17 20](https://user-images.githubusercontent.com/22118377/40636536-471bcc84-62b4-11e8-8369-c3aad49b8817.png)

[Crash Report](https://pastebin.com/zHpyqskZ)

**Comment by boq** [comment]
Sorry, this is not going to happen.
a) It's MC 1.7.10, which is already unsupported
b) Optifine is not supported
c) In this particular case, it's not possible to implement it correctly without support from both sides
