### ISSUE TITLE
Gravestones don't contain soulbound items

### ISSUE THREAD

**Issue by TheRedMelon** [OpenMods/OpenBlocks#916]
I had two tinkers' tools with soulbound and my armour had the soulbound enchantment from EnderIO.  I was not wearing the armour, it was in my inventory.  These items were removed from my inventory and didn't drop when I broke my gravestone.

The items were obviously saved in the death inventory save (as I used this to get them back), but not in the grave save.

**Comment by boq** [comment]
Unfortunately, it's not something we can fix on our side - grave just stores everything it gets, but actual contents are depending on other mods' handlers that run before it. We have small manual on debugging graves [here](https://openmods.info/faq.html#ob-0).

**Comment by ryantheleach** [comment]
@TheRedMelon Where you using SpongeForge at all? We have had reoccurring issues regarding graves and correctly recording item drops with them, and are currently investigating issues with other grave mods.

**Comment by TheRedMelon** [comment]
No, I am using ordinary forge.
