### ISSUE TITLE
Crashes on Preinitialization (Intel G45/43 Graphics)

### ISSUE THREAD

**Issue by masternetra** [OpenMods/OpenBlocks#917]
Tried playing the Skycolonies modpack and tested it by itself and each time game crashes at preinitialization. Here are the results.

**Forge Version:** 14.23.4.2709
**Openblocks Version:** 1.12.2-1.7.6
**OpenModsLib Version:** 1.12.2-0.11.5

**Log:** https://pastebin.com/Hx8VyViM

**Graphics Card:** Intel G45/43

**Java Error Report:**
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	javaw.exe
  Application Version:	8.0.1710.11
  Application Timestamp:	5abc22fc
  Fault Module Name:	StackHash_70cf
  Fault Module Version:	6.1.7601.24150
  Fault Module Timestamp:	5b0cbc1e
  Exception Code:	c0000374
  Exception Offset:	00000000000bf6b2
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	70cf
  Additional Information 2:	70cf790984089c68d8c6286c3ac52100
  Additional Information 3:	d019
  Additional Information 4:	d01979b65ae21829a6572ca65dbf5c98
```
**Addtional Notes:**
Have a simlair issue with Immersive Engineering, according to the Dev there it was (with IE) a OpenGL issue. Mod is using OpenGL stuff that my card didn't support (My Graphics card can only handle up to OpenGL 2.1) and that while Vanilla Minecraft is suppose to handle such issue by disabling such features the code that handles that seems to be broke. Possibly a simlair issue with Openblocks? If this can be resolved by disabling some stuff in config would like to know what.

**Comment by masternetra** [comment]
The log I linked to from Pastebin is .minecraft/logs/latest. there is no "fml-client-latest" in that directory.

**Comment by boq** [comment]
That's what I wanted.

You may try to set option `renderingEnabled` in `skyblock` category to false. Not sure

**Comment by masternetra** [comment]
It worked, minecraft loaded after doing that. At least the standlone where it was just your mod did, skycolonies modpack got further but crashed just after getting to the minecraft main menu screen, probably not a issue involving openblocks at this point though.
