### ISSUE TITLE
Skyblocks are gray even if force enabled via config

### ISSUE THREAD

**Issue by TheRealDadbeard** [OpenMods/OpenBlocks#927]
OpenBlocks-1.12.2-1.7.6
OpenModsLib-1.12.2-0.11.5
OptiFine_1.12.2_HD_U_E2

I enabled it in the config but they are still gray. No errors nothing.

**Comment by boq** [comment]
Please attach logs - if something went wrong during initialization, it should be in there.

Also, just to be sure: they are powered or inverted, right?

**Comment by TheRealDadbeard** [comment]
[latest.log](https://github.com/OpenMods/OpenBlocks/files/2300388/latest.log)

Removing Optifine works propably but is no solution for me.
Yes of course powered or inverted.

**Comment by boq** [comment]
`[11:10:09] [main/INFO]: openblocks.client.renderer.SkyBlockRenderer.setup(SkyBlockRenderer.java:88): Framebuffer not enabled`

Framebuffers are required for skyblocks. You can enable it in options.

**Comment by TheRealDadbeard** [comment]
But there is nothing in the config files for it??

**Comment by boq** [comment]
In vanilla it's in `options.txt`, under `fboEnable`. Not sure how Optifine manages that.

Note: It's bad idea to enable skyblocks if you have shaders enabled

**Comment by TheRealDadbeard** [comment]
It's enabled in there hmmm. Then maybe Optifine fiddling with it?

**Comment by boq** [comment]
Maybe. I can only say "worksforme(TM)".

**Comment by TheRealDadbeard** [comment]
Yeah it works without optifine. Will make a issue over there. Thanks for your help!
