### ISSUE TITLE
[1.12.2] Crane holding a chest voids contents if you place it over a chest

### ISSUE THREAD

**Issue by JAWSAWN** [OpenMods/OpenBlocks#930]
Steps to reproduce:
Place a chest in the world
Use the crane backpack on a filled chest and pick it
Place the chest over the other chest
Chest will pop up but its contents will be lost

**Comment by JAWSAWN** [comment]
Actually releasing the chest can cause that too

**Comment by boq** [comment]
Fixed on OpenModsLib snapshot 516
