### ISSUE TITLE
Auto enchanment table not accepting liquid xp

### ISSUE THREAD

**Issue by Larsm1980** [OpenMods/OpenBlocks#931]
Hi its accepting items from chests but not liquid xp
it standing on a openblocks tank but its not accepting it.. i have turned it on by right clicking turning the table and left clicking the bottom.

**Comment by boq** [comment]
Is "auto drink" option checked?

**Comment by Larsm1980** [comment]
yes. i fund out whats off the xp from mobs is not the same as the one from players.. im gonna try to use the unifier and see if that works.. thanks.
