### ISSUE TITLE
[1.12.2] XP dupe/increase with drains/showers

### ISSUE THREAD

**Issue by 2called-chaos** [OpenMods/OpenBlocks#933]
(Supposedly) standing in between 4 drains leads to XP duplication (slow increase, the more XP the more you dupe).

Demonstration in Revelations pack 2.3.0 SMP: https://www.youtube.com/watch?v=jrQm7kzQmms&t=4m57s

**Comment by boq** [comment]
It was problem with shower and small amount of leftovers in tank (nothing to do with drains). Anyway, fixed.
