### ISSUE TITLE
A user keeps crashing

### ISSUE THREAD

**Issue by sfxworks** [OpenMods/OpenBlocks#934]
-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 645426576 bytes (615 MB) / 2937585664 bytes (2801 MB) up to 2937585664 bytes (2801 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.4.2705 102 mods loaded, 102 mods active-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 645426576 bytes (615 MB) / 2937585664 bytes (2801 MB) up to 2937585664 bytes (2801 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.4.2705 102 mods loaded, 102 mods active

openblocks  OpenBlocks-1.12.2-1.7.6

They provide these reports when they crash. Happens 3 times a day to this user. 

https://gist.github.com/sfxworks/43dd496fbbdb26276de6a9a182f7eb7e

**Comment by boq** [comment]
This is caused by interaction with TexFix. Anyway, due to changes in OpenBlocks, this issue should be gone in next version.

**Comment by Swiftcreepa** [comment]
About how long will it be till the new version, no rush.
