### ISSUE TITLE
Open Blocks Golden Egg

### ISSUE THREAD

**Issue by manmaed** [OpenMods/OpenBlocks#936]
## Bug Report
Open Blocks Golden Egg crashes game

## Steps to Reproduce (for bugs)
1. Craft OpenBlocks Golden Egg
2. Sit on egg
3. wait for it to do its thing
4. Boom Crash!

## Logs
* Client/Server Log: https://pastebin.com/yWNSwUSC

## Client Information
* Modpack Version: StoneBlocks 1.0.17 (with ThermalInnovation-1.12.2-0.3.0.7-universal installed)
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No
* Tested in Singleplay and it works fine 
* https://github.com/Sunekaer/stoneBlock/issues/234#issue-365464745

**Comment by boq** [comment]
Fixed in OpenModsLib (will be released as 0.12.1).
