### ISSUE TITLE
Cannot disable grave

### ISSUE THREAD

**Issue by 88880** [OpenMods/OpenBlocks#943]
I am playing RAD modpack and I want to disable graves so I can set keepinventory gamerule. I disabled graves yet it keeps creating one, and when I disable grave generation from commands, it doesn't let me keep my inventory after I set the gamerule. Can someone help?

**Comment by boq** [comment]
[Disabling graves](https://openmods.info/faq.html#ob-2), [Sanity check](https://openmods.info/faq.html#ob-3) - I see this pack also includes Tomb Many Graves 2. If that fails, [debugging]  may help (https://openmods.info/faq.html#ob-0).
