### ISSUE TITLE
Config Option to not spawn with guide

### ISSUE THREAD

**Issue by coldReactive** [OpenMods/OpenBlocks#949]
I saw this issue: https://github.com/OpenMods/OpenBlocks/issues/322

And wonder where it is. Do I really have to go into a file for the mod to change this? When pretty much all other mods have a mod config option for it? I've tried disabling all of the "infoguide" options in mod config, but it still doesn't stop the book from spawning. (It doesn't help nothing has tooltips to tell me what does what.)

The Akashic Tome can be altered with NBT Data to have your infoguide in it, and modpacks like all the mods allows you to craft an Akashic Tome with all of the guidebooks for all of its mods with just a block of dirt. Which is what I'm doing for my own modpack as well. Which is why I want to know how to go about doing this.

**Comment by boq** [comment]
```
    # Should every player get info book on first login
    B:infoBook=true
```

**Comment by coldReactive** [comment]
It's already set to false.
