### ISSUE TITLE
1.12.2 Block breaker dupes Skulls

### ISSUE THREAD

**Issue by tigerdan2** [OpenMods/OpenBlocks#952]
Version
1.12.2-1.8

Placing one skull infront of  a powered block breaker will drop two skulls
(tested in ftb sky adventures, enigmatica2, and a few other packs. not yet with openblocks alone)

**Comment by Fayti1703** [comment]
Can confirm with just OpenModsLib (`0.12.1-snapshot-521`) and OpenBlocks (`1.8-snapshot-838`). Previous powered state of the block breaker does not matter, any block breaker breaking any skull will cause two of that skull to drop.

**Comment by boq** [comment]
Fixed in OpenModsLib.
