### ISSUE TITLE
Infinite XP glitch in version 1.8

### ISSUE THREAD

**Issue by eponymousjayk** [OpenMods/OpenBlocks#956]
Placing blocks in this configuration (with the XP shower attached directly to the tank on the upper right):

![2019-01-21 13-28-24 -0600](https://user-images.githubusercontent.com/14890072/51495276-668cc900-1d81-11e9-8933-f28c8731ebee.png)

causes XP to go up indefinitely:

![2019-01-21 13-29-28 -0600](https://user-images.githubusercontent.com/14890072/51495287-6ee50400-1d81-11e9-9f64-7c570cbe600f.png)

I started with about 15 XP in the tank. Seems standing further away from the shower while remaining on the XP drain exacerbates the issue.

This is in version 1.8 with the latest FTB Revelations modpack.

**Comment by boq** [comment]
It's interaction with Clumps. Still investigating.

**Comment by boq** [comment]
Ok, found it: when looking for candidate orbs for merging, Clumps does not check `Entity.isDead`, so orb can be used even after it was picked by player.
