### ISSUE TITLE
[1.12.2] Saves are not loadable after OB have been removed

### ISSUE THREAD

**Issue by NickelHub** [OpenMods/OpenBlocks#957]
Recently, I removed Open Blocks from my modpack. After that I wasn't unable anymore to load my world. The crash files are server files but I joined a single player world. Seems that removing OB corrupting the level.dat file though. 

Before deleting Myscraft's stuff from save. See also: https://github.com/XCompWiz/Mystcraft-Issues/issues/335
[crash-2019-01-23_17.25.12-server.txt](https://github.com/OpenMods/OpenBlocks/files/2788760/crash-2019-01-23_17.25.12-server.txt)

After deleting Mystcraft's stuff. 
[crash-2019-01-23_19.32.56-server.txt](https://github.com/OpenMods/OpenBlocks/files/2788758/crash-2019-01-23_19.32.56-server.txt)

After adding back OB no crash appears. 

Note that I tested different forge versions: 2795, 2796, 2808.

**Comment by boq** [comment]
Does not seem to be related directly to OpenBlocks, seems like something is messing with Mystcraft. We are not doing anything with dimensions or do any hacks on persistent data.

I would suspect JustEnoughIDs or similar, they usually take mod removal poorly.

**Comment by NickelHub** [comment]
Do you know a way to solve this?

**Comment by boq** [comment]
At this point? Probably no way to solve it. It's just a risk of using ID extenders.

**Comment by NickelHub** [comment]
Then it is mistake by GravestoneMod. 
I found this in the log. Removing GravestoneMod solves the crash. The mod is creating corpse for each villager professions. Missing profession causes the null.

https://pastebin.com/qUyabbVT

**Comment by Veovis-Muaddib** [comment]
That makes sense, thanks for the update.
