### ISSUE TITLE
OpenBlocks requires openmods

### ISSUE THREAD

**Issue by JJ2001** [OpenMods/OpenBlocks#958]
When I try to load Minecraft it comes up with the message 'You must include the right dependencies for OpenBlocks: Requires openmods 0.12 or above, and below 0.13 (missing)' however I already have OpenModsLib-1.12.2-0.12.1 is this the incorrect file?

**Comment by boq** [comment]
Latest files from Curse are always verified to be working. You either have wrong files, misplaced them or misconfigured your launcher (if non-vanilla is used).
