### ISSUE TITLE
Block Placer causing Duping Bug [Solved]

### ISSUE THREAD

**Issue by DevilsWings** [OpenMods/OpenBlocks#959]
Tested in openblocks 1.8 PO3 environment, Block placer doesn't consumes blocks in its own inventory yet places a block, causing item duping to be viable. #

**Comment by boq** [comment]
Can't reproduce with just OpenBlocks. I will need more information:
- what is in front of placer
- what are you trying to place
- how do you trigger it?

**Comment by DevilsWings** [comment]
- Air Blocks(i.e. nothing)

- Wood log/Iron blocks, basically anything arbitrary

- Tried triggering it with Timer from RF tools and just a vanilla buttons, both methods works
It seems like a pretty generic issue imo, if it can't be reproduced, I do believe it would be a problem on PO3

**Comment by DevilsWings** [comment]
Problem seems to be coming from the PO3 server files, guess those server files really aren't ready yet
