### ISSUE TITLE
Glyphs crashing game

### ISSUE THREAD

**Issue by bba3075** [OpenMods/OpenBlocks#960]
Whenever Jei tries to load the glyphs the game crashes.
[crash-2019-03-13_21.09.09-client.txt](https://github.com/OpenMods/OpenBlocks/files/2964268/crash-2019-03-13_21.09.09-client.txt)
My friends have the same exact mods as me, it does not crash them.

**Comment by boq** [comment]
#948 duplicate, disable anisotropic filtering or anti-aliasing in Optifine
