### ISSUE TITLE
Game Crash during loading

### ISSUE THREAD

**Issue by Sarnow** [OpenMods/OpenBlocks#964]
The game crashes during loading, If I remove Open Blocks from the game it loads just fine.
[crash-2019-03-23_12.42.09-client.txt](https://github.com/OpenMods/OpenBlocks/files/2999739/crash-2019-03-23_12.42.09-client.txt)

**Comment by boq** [comment]
`java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.` - i.e. number of modded block types hit hard limit - there is not much to do and it's certainly not related to OpenBlocks. Also, it happened during `tinyprogressions` initialization, but that's not really relevant.

**Comment by Sarnow** [comment]
Thanks for the info, I was not sure how to read what was wrong, just knew it happened only when i added open blocks.
