### ISSUE TITLE
Building guide ghostblock/shader

### ISSUE THREAD

**Issue by SodaSpartan** [OpenMods/OpenBlocks#966]
While running a shader pack, the ghost blocks from the building guide almost disappear. For now shader needs to be disabled to see them.
1.12.2

**Comment by boq** [comment]
You can try alternative method of drawing markers by setting `useAdvancedRenderer` to `false` in config.

**Comment by SodaSpartan** [comment]
Thank you for your suggestion, but I was unable to see a difference between the two options.  You can see the ghost block if while looking through it there is a block somewhere behind it, but if while looking through it you are looking at sky or deep water the are nearly invisible.  Im going to try some other shaders to see if it is a common problem but for now the following picture is what it looks like.
![2019-04-05_02 09 34](https://user-images.githubusercontent.com/11382410/55610123-e3f09480-5747-11e9-83b4-b65e2cbe96fe.png)

**Comment by SodaSpartan** [comment]
I have tried a few other packs and it works just fine in most of them but packs such as kuda(as shown above) and SEUS packs show some distortion in every version i tried though with SEUS you can see the blocks fine, they just look strange. tbh i think this is a problem on the shaders side not open blocks so im going to close this.
![2019-04-05_02 36 46](https://user-images.githubusercontent.com/11382410/55611670-cd4c3c80-574b-11e9-9510-61ce93ccf290.png)
