### ISSUE TITLE
crash after installing

### ISSUE THREAD

**Issue by aceofknights** [OpenMods/OpenBlocks#967]
[crash-2019-04-01_03.20.13-client.txt](https://github.com/OpenMods/OpenBlocks/files/3028164/crash-2019-04-01_03.20.13-client.txt)
not very tech savy could use some help

playing skyfactory 3 added open blocks and openmods crashed when i was searching through nei twice.

**Comment by boq** [comment]
That's crash is in https://github.com/iChun/GooglyEyes
