### ISSUE TITLE
No textures from paint? [1.12.2]

### ISSUE THREAD

**Issue by hayross2** [OpenMods/OpenBlocks#979]
Whenever I try and use the paint bucket, the result is that whatever block I click gets colored correctly, but in a completely flat texture like so: https://imgur.com/a/7A7ENVq

This seems to be the case for all blocks that I can find. I'm no expert in minecraft modding or submitting bug reports in general, so if someone could explain to me what further information I'd need to give, that would be helpful, thank you

**Comment by boq** [comment]
This is expected behavior, paint fully covers texture. Main purpose of paintbrush was not tinting, but placing patterns via stencils.
