### ISSUE TITLE
[Mod compat][NEI] Chunk boundary/light level overlays cannot be displayed by NEI

### ISSUE THREAD

**Issue by Twisted-Code** [OpenMods/OpenBlocks#983]
I don't know which side of the fence this is on, but after installing OB 1.8.1 in a pack I'm developing, pressing NEI's keybind to display chunk boundaries, regardless of whether I leave it on the default "F9" or change it to something new, no longer works.
Debug log.: [debug.log](https://github.com/OpenMods/OpenBlocks/files/3645000/debug.log)
if there's any more information you need, I'll do my best to provide it, but I honestly am not sure what caused this. I just know it involves OB

**Comment by Twisted-Code** [comment]
oh by the way, as the above title change indicates, the same thing applies to NEI's light level overlay. Not sure if that's significant but information is information, ya know?

**Comment by Twisted-Code** [comment]
after trying to reproduce it on a different computer (that also has both mods installed), I'm not so sure it's actually caused by this mod, or at least not by simply adding the mod. Nonetheless, the addition of OpenBlocks, so far as I'm aware, is the only thing that changed before I first noticed the problem (hence why I'm not going to close my issue yet).

**Comment by boq** [comment]
Unfortunately, with that amount of blocks, I'm unable to diagnose rendering problems like this. Though you may experiment with disabling `hook_pre_world_rendering` in `OpenModsLibCore.json` config, since it's probably only thing that may change something.

**Comment by Twisted-Code** [comment]
Okay, I understand. If I continue to have problems after disabling that, or if disabling that breaks something else for me, I'll try to reproduce the issue on a scaled-down version of my pack so you have less blocks to deal with. In the meantime, however, I'll consider this issue resolved, as it doesn't seem to happen consistently anyway and I don't want to bother you further at this time. Thanks!
