### ISSUE TITLE
Paintbrushes replace blocks with canvas despite config

### ISSUE THREAD

**Issue by katubug** [OpenMods/OpenBlocks#985]
Hi! So, I changed this config setting from the default `true` to `false`:

```
# If true, paintbrush will replace suitable blocks with canvas. Otherwise, it will only try to paint blocks
    B:paintbrushReplacesBlocks=false
```
I'm not sure how this is intended to work, but I'm not sure it's functioning correctly. With the config set to false, paintbrushes can no longer be right clicked on blocks without a stencil on them (unless they were previously painted). However, as far as I can tell, it still replaces the blocks with canvas every time. Tested on sand, stone, diorite, cobblestone, oak planks. Everything turned to canvas.

I know it says "try" - but my expectation was that it would at least work with vanilla blocks.

**Comment by boq** [comment]
Can't reproduce. With this flag set to false, it only works on blocks that implement their own recoloring (like wool), but even then it will still be wool.

Are you playing on server? Since changing that just on client does not work.

**Comment by katubug** [comment]
Ah, I misunderstood how they worked. I didn't test it with wool, so it's most likely functioning as intended. Thanks for the explanation!
