### ISSUE TITLE
OpenBlocks Grave didn't spawn and ob_restore command says it restored but no items are given.

### ISSUE THREAD

**Issue by robbins** [OpenMods/OpenBlocks#992]
My world was loading (and was taking a longer time than usual to load), and once it loaded in I wasn't paying attention and almost immediately after I loaded in it said I blew up due to a creeper. I respawned at my base with no items. I didn't feel like going to the grave, so I ran

`/ob_inventory restore SimplyGamingYTZ SimplyGamingYTZ-2019-12-26_23.18.26-death-0`

and it said "Restored Inventory for player SimplyGamingYTZ". However, no items were given to me. So I teleported to the death waypoint, and found no grave!
![image](https://user-images.githubusercontent.com/31457698/71501390-4474b400-2838-11ea-8dcd-8a8e12cfe61e.png)

You can see how the date and time on the waypoint matches the restore command. In the list I could restore from, there is no grave file, only death file. 
![image](https://user-images.githubusercontent.com/31457698/71501407-5e15fb80-2838-11ea-941a-bb10490e5a69.png)

So, I navigated to the folder and saw "inventory-SimplyGamingYTZ-2019-12-26_23.18.26-death-0.dat". It has a size of 217 bytes, does this contain my inventory? I opened it in NBTExplorer and it says 
![image](https://user-images.githubusercontent.com/31457698/71501446-99b0c580-2838-11ea-9aae-649f0f57583f.png) that but I can't see any items that were in my inventory.

Is this a lost cause or is there some way to get it back? I'm so frustrated and I died of something I couldn't control, the moment I loaded in it said I died, so maybe MC couldn't log it in time or something?

All help is appreciated! Thanks :)

**Comment by robbins** [comment]
Here's the log: https://pastebin.com/vxUEfMtL

**Comment by boq** [comment]
This usually happens when other mod is clearing items before inventory can be saved.

To confirm that, please attach actual log file (not just console log). 

For more information and procedure for finding out interfering mods, please read https://openmods.info/faq.html#ob-0

**Comment by robbins** [comment]
I have neither of the 3 mods listed there. Is the actual log file the .log.gz ones?

If so it should be this one: 
[2019-12-26-4.log.gz](https://github.com/OpenMods/OpenBlocks/files/4005879/2019-12-26-4.log.gz)

Thanks.

**Comment by boq** [comment]
It seems log lines I was looking for have not been stored (might be launcher) thing.

Anyway, most probable explanation is that inventory was already empty at moment of death. I don't see anything explicitly related to OpenBlocks.

**Comment by robbins** [comment]
Ah damn, idk why that would happen :( Luckily tho I found another grave.dat file with my TiCon hammer which was the main thing I wanted back so I was able to read what I had on it. Lost the other stuff, but at least I got that. Thanks for trying to help though, first time this has ever happened to me.
