### ISSUE TITLE
Hang Glider makes weird high pitched sounds when flying

### ISSUE THREAD

**Issue by bryinabrt** [OpenMods/OpenBlocks#997]
Using The 1.12.2 Pack + Optfine and shaders, for some reason the hang glider makes high pitched sounds like its a radio or something. Heres a video of the sound: https://streamable.com/ytaz9

**Comment by boq** [comment]
You have enabled [variometer](https://en.wikipedia.org/wiki/Variometer). Default keybind for that is `V`.
